[mcp_servers.aseprite]
command = 'C:\Users\jeron\AppData\Local\Programs\Python\Python312\Scripts\uv.exe'

args = [
  "--directory",
  'C:\Users\jeron\Desktop\aseprite-mcp',
  "run",
  "--frozen",
  "-m",
  "aseprite_mcp"
]

env = {
  ASEPRITE_PATH = 'C:\Program Files (x86)\Steam\steamapps\common\Aseprite\Aseprite.exe'
}

enabled = true
startup_timeout_sec = 20
tool_timeout_sec = 60
default_tools_approval_mode = "prompt"

disabled_tools = [
  "run_lua_script",
  "audit_animation",
  "animation_sanitize",
  "start_preview_server",
  "stop_preview_server"
]