// Seam B frames: hello, snapshot, subscribe, commands, events (05 §2.1 `host-protocol/`).
export * from './adr-003'
export * from './endpoint'
export * from './envelope'
export * from './errors'
export * from './capabilities'
export * from './frameCodec'
export * from './protocolVersion'
export * from './requestId'
export * from './params'
export type { HostMethods } from './methods'
export { HOST_FRAME_SCHEMAS, type HostFrames } from './frames'
