// GENERATED by `pnpm ipc:generate` (scripts/ipc/generate-window-api.mjs) — do not edit by hand (22 §5).
// The preload: `window.api`, one member per registry row (14 §2.1; ADR-033 item 6; ADR-019 item 1).
// Source: the channel registry (src/contracts/ipc) and the route table's shapes (src/ui-main/ipc/routes.ts).
//
// Each member speaks on its row's wire with the types of the shape its route uses in this release; it coerces for
// ergonomics and never throws (a value it cannot coerce is passed on for main to refuse; a payload structured clone
// cannot copy is dropped by a send and rejected by an invoke, 14 §1.4). Built as one
// CommonJS script whose only runtime import is `electron`, so it loads in a sandboxed renderer (S-019-1).
import { contextBridge, ipcRenderer, webUtils, type IpcRendererEvent } from 'electron'
import type { z } from 'zod'
import type { CHANNELS, ChannelKey } from '@dwarfai/contracts'
import type { TODAY } from '../contracts/ipc/todayShapes'

/** A request as the renderer hands it over: the preload never mutates it, so an array may be readonly. */
type Accepted<T> = T extends readonly (infer I)[]
  ? readonly Accepted<I>[]
  : T extends File
    ? T
    : T extends object
      ? { [P in keyof T]: Accepted<T[P]> }
      : T
/** A row's today shape (21 §1 item 2a): its TODAY_SHAPES entry, or its registry entry for a KEEP row. */
type TodayRow<K extends ChannelKey> = K extends keyof typeof TODAY
  ? (typeof TODAY)[K]
  : (typeof CHANNELS)[K]
type TodayRequest<K extends ChannelKey> = Accepted<z.input<TodayRow<K>['request']>>
type TodayResult<K extends ChannelKey> = z.output<TodayRow<K>['response']>
/** A row's target shape (14): its registry entry. */
type TargetRequest<K extends ChannelKey> = Accepted<z.input<(typeof CHANNELS)[K]['request']>>
type TargetResult<K extends ChannelKey> = z.output<(typeof CHANNELS)[K]['response']>

/** An id or a text as a string, or '' which main refuses. */
function textOf(value: unknown): string {
  return typeof value === 'string' ? value : ''
}

/** Today's provider names (the today launch request's enum); an unknown one crosses as '', never a default. */
const PROVIDERS: readonly unknown[] = ['claude', 'codex', 'antigravity', 'opencode']
function providerOf(value: unknown): string {
  return typeof value === 'string' && PROVIDERS.includes(value) ? value : ''
}

/**
 * An answer rebuilt from string pairs only. The person's own words (`text`) cross alone, never beside a record;
 * a non-string value is dropped, so main refuses an answer that names no option.
 */
function questionAnswerOf(request: unknown): Record<string, unknown> {
  const record =
    typeof request === 'object' && request !== null ? (request as Record<string, unknown>) : {}
  const address = { dwarfId: textOf(record.dwarfId), toolUseId: textOf(record.toolUseId) }
  if (record.text !== undefined) {
    return { ...address, ...(typeof record.text === 'string' ? { text: record.text } : {}) }
  }
  const answers = stringPairsOf(record.answers)
  const ownWords = stringPairsOf(record.ownWords)
  return { ...address, answers, ...(Object.keys(ownWords).length === 0 ? {} : { ownWords }) }
}
function stringPairsOf(value: unknown): Record<string, string> {
  const pairs: Record<string, string> = {}
  if (typeof value !== 'object' || value === null) return pairs
  for (const [key, entry] of Object.entries(value))
    if (typeof entry === 'string') pairs[key] = entry
  return pairs
}

/** A one-way message that cannot cross (structured clone refuses it) is dropped, never thrown (14 §1.4). */
function sendOrDrop(send: () => void): void {
  try {
    send()
  } catch {
    // Dropped: main never receives it, as it would drop a one-way payload it refuses.
  }
}

/** A request always answers with a promise: one that cannot cross rejects, never throws (14 §1.4). */
function invokeOrReject<T>(invoke: () => Promise<T>): Promise<T> {
  try {
    return invoke()
  } catch (error) {
    return Promise.reject(error instanceof Error ? error : new Error(String(error)))
  }
}

/** API surface exposed to the renderer as `window.api`. */
export interface DwarfAiMinersApi {
  /** A-01 · `panel:hide` · send · KEEP · target shape */
  hidePanel: () => void
  /** A-02 · `panel:raise` · send · KEEP · target shape */
  raisePanel: () => void
  /** A-03 · `panel:getAlwaysOnTop` · invoke · KEEP · target shape */
  getAlwaysOnTop: () => Promise<TargetResult<'panel:getAlwaysOnTop'>>
  /** A-04 · `panel:setAlwaysOnTop` · invoke · KEEP · target shape */
  setAlwaysOnTop: (
    request: TargetRequest<'panel:setAlwaysOnTop'>
  ) => Promise<TargetResult<'panel:setAlwaysOnTop'>>
  /** A-05 · `panel:visible:get` · invoke · KEEP · target shape */
  getPanelVisible: () => Promise<TargetResult<'panel:visible:get'>>
  /** A-06 · `audio:preferences:get` · invoke · KEEP · target shape */
  getAudioPreferences: () => Promise<TargetResult<'audio:preferences:get'>>
  /** A-07 · `audio:preferences:set` · invoke · KEEP · target shape */
  setAudioPreferences: (
    request: TargetRequest<'audio:preferences:set'>
  ) => Promise<TargetResult<'audio:preferences:set'>>
  /** A-08 · `panel:layout:get` · invoke · KEEP · target shape */
  getPanelLayout: () => Promise<TargetResult<'panel:layout:get'>>
  /** A-09 · `panel:layout:set` · invoke · KEEP · target shape */
  setPanelLayout: (
    request: TargetRequest<'panel:layout:set'>
  ) => Promise<TargetResult<'panel:layout:set'>>
  /** A-10 · `shortcut:get` · invoke · KEEP · target shape */
  getToggleShortcut: () => Promise<TargetResult<'shortcut:get'>>
  /** A-11 · `shortcut:set` · invoke · KEEP · target shape */
  setToggleShortcut: (
    request: TargetRequest<'shortcut:set'>
  ) => Promise<TargetResult<'shortcut:set'>>
  /** A-12 · `mines:get` · invoke · RETIRE · target shape */
  getMines: () => Promise<TargetResult<'mines:get'>>
  /** A-13 · `dwarf:activate` · invoke · CHANGE · today shape */
  activateDwarf: (request: TodayRequest<'dwarf:activate'>) => Promise<TodayResult<'dwarf:activate'>>
  /** A-14 · `dwarf:feed` · invoke · RETIRE · target shape */
  getDwarfFeed: (request: TargetRequest<'dwarf:feed'>) => Promise<TargetResult<'dwarf:feed'>>
  /** A-15 · `dwarf:feed:page` · invoke · CHANGE · target shape */
  getDwarfFeedPage: (
    request: TargetRequest<'dwarf:feed:page'>
  ) => Promise<TargetResult<'dwarf:feed:page'>>
  /** A-16 · `panel:watchDwarfFeed` · send · RETIRE · target shape */
  setWatchedDwarf: (request: TargetRequest<'panel:watchDwarfFeed'>) => void
  /** A-17 · `dwarf:refreshTelemetry` · send · RETIRE · target shape */
  refreshDwarfTelemetry: (request: TargetRequest<'dwarf:refreshTelemetry'>) => void
  /** A-18 · `dwarf:setTuning` · invoke · RETIRE · target shape */
  setDwarfTuning: (
    request: TargetRequest<'dwarf:setTuning'>
  ) => Promise<TargetResult<'dwarf:setTuning'>>
  /** A-19 · `mine:history` · invoke · CHANGE · target shape */
  getMineHistory: (request: TargetRequest<'mine:history'>) => Promise<TargetResult<'mine:history'>>
  /** A-20 · `mine:openPath` · invoke · KEEP · target shape */
  openMinePath: (request: TargetRequest<'mine:openPath'>) => Promise<TargetResult<'mine:openPath'>>
  /** A-21 · `shell:openExternalLink` · invoke · KEEP · target shape */
  openExternalLink: (
    request: TargetRequest<'shell:openExternalLink'>
  ) => Promise<TargetResult<'shell:openExternalLink'>>
  /** A-22 · `shell:copyText` · invoke · KEEP · target shape */
  copyText: (request: TargetRequest<'shell:copyText'>) => Promise<TargetResult<'shell:copyText'>>
  /** A-23 · `dwarf:sendText` · invoke · CHANGE · today shape */
  sendDwarfText: (request: TodayRequest<'dwarf:sendText'>) => Promise<TodayResult<'dwarf:sendText'>>
  /** A-24 · `dwarf:attachments:choose` · invoke · KEEP · target shape */
  chooseDwarfAttachments: () => Promise<TargetResult<'dwarf:attachments:choose'>>
  /** A-25 · `dwarf:attachments:describe` · invoke · KEEP · today shape */
  describeDwarfAttachments: (
    request: TodayRequest<'dwarf:attachments:describe'>
  ) => Promise<TodayResult<'dwarf:attachments:describe'>>
  /** A-26 · `dwarf:kick` · invoke · RETIRE · today shape */
  kickDwarf: (request: TodayRequest<'dwarf:kick'>) => Promise<TodayResult<'dwarf:kick'>>
  /** A-27 · `dwarf:retire` · send · RETIRE · today shape */
  retireDwarf: (request: TodayRequest<'dwarf:retire'>) => void
  /** A-28 · `app:build` · invoke · KEEP · target shape */
  getAppBuild: () => Promise<TargetResult<'app:build'>>
  /** A-29 · `app:features` · invoke · KEEP · target shape */
  getFeatureFlags: () => Promise<TargetResult<'app:features'>>
  /** A-30 · `mine:declare` · invoke · KEEP · target shape */
  declareMine: () => Promise<TargetResult<'mine:declare'>>
  /** A-31 · `mine:declare-main` · invoke · KEEP · target shape */
  declareMainProject: () => Promise<TargetResult<'mine:declare-main'>>
  /** A-32 · `mine:undeclare` · invoke · KEEP · target shape */
  undeclareMine: (
    request: TargetRequest<'mine:undeclare'>
  ) => Promise<TargetResult<'mine:undeclare'>>
  /** A-33 · `metrics:reset` · invoke · CHANGE · target shape */
  resetMetrics: (request: TargetRequest<'metrics:reset'>) => Promise<TargetResult<'metrics:reset'>>
  /** A-34 · `projects:query` · invoke · KEEP · target shape */
  queryProjects: (
    request: TargetRequest<'projects:query'>
  ) => Promise<TargetResult<'projects:query'>>
  /** A-35 · `agent:launch` · invoke · CHANGE · today shape */
  launchAgent: (request: TodayRequest<'agent:launch'>) => Promise<TodayResult<'agent:launch'>>
  /** A-36 · `agent:providers` · invoke · CHANGE · today shape */
  listAgentProviders: () => Promise<TodayResult<'agent:providers'>>
  /** A-37 · `agent:models` · invoke · RETIRE · today shape */
  listAgentModels: () => Promise<TodayResult<'agent:models'>>
  /** A-38 · `agent:launchHeld` · invoke · RETIRE · today shape */
  launchHeldSession: (
    request: TodayRequest<'agent:launchHeld'>
  ) => Promise<TodayResult<'agent:launchHeld'>>
  /** A-39 · `agent:launchHosted` · invoke · CHANGE · today shape */
  launchHostedProcess: (
    request: TodayRequest<'agent:launchHosted'>
  ) => Promise<TodayResult<'agent:launchHosted'>>
  /** A-40 · `agent:answerQuestion` · invoke · CHANGE · today shape */
  answerDwarfQuestion: (
    request: TodayRequest<'agent:answerQuestion'>
  ) => Promise<TodayResult<'agent:answerQuestion'>>
  /** A-41 · `agent:answerPermission` · invoke · CHANGE · today shape */
  answerDwarfPermission: (
    request: TodayRequest<'agent:answerPermission'>
  ) => Promise<TodayResult<'agent:answerPermission'>>
  /** A-42 · `notifications:enabled:get` · invoke · KEEP · today shape */
  getNotificationsEnabled: () => Promise<TodayResult<'notifications:enabled:get'>>
  /** A-43 · `notifications:enabled:set` · invoke · KEEP · today shape */
  setNotificationsEnabled: (
    request: TodayRequest<'notifications:enabled:set'>
  ) => Promise<TodayResult<'notifications:enabled:set'>>
  /** A-44 · `presence:visibleMines` · send · CHANGE · target shape */
  reportVisibleMines: (request: TargetRequest<'presence:visibleMines'>) => void
  /** A-45 · `typography:preferences:get` · invoke · KEEP · target shape */
  getTypographyPreferences: () => Promise<TargetResult<'typography:preferences:get'>>
  /** A-46 · `typography:preferences:set` · invoke · KEEP · target shape */
  setTypographyPreferences: (
    request: TargetRequest<'typography:preferences:set'>
  ) => Promise<TargetResult<'typography:preferences:set'>>
  /** A-47 · `jev:settings:get` · invoke · KEEP · today shape */
  getJevSettings: () => Promise<TodayResult<'jev:settings:get'>>
  /** A-48 · `jev:apiKey:set` · invoke · KEEP · today shape */
  setJevApiKey: (request: TodayRequest<'jev:apiKey:set'>) => Promise<TodayResult<'jev:apiKey:set'>>
  /** A-49 · `jev:apiKey:clear` · invoke · KEEP · today shape */
  clearJevApiKey: () => Promise<TodayResult<'jev:apiKey:clear'>>
  /** A-50 · `jev:route` · invoke · CHANGE · today shape */
  routeJevLaunch: (request: TodayRequest<'jev:route'>) => Promise<TodayResult<'jev:route'>>
  /** A-51 · `jev:preferences:set` · invoke · KEEP · today shape */
  setJevPreferences: (
    request: TodayRequest<'jev:preferences:set'>
  ) => Promise<TodayResult<'jev:preferences:set'>>
  /** A-52 · `opencode:settings:get` · invoke · CHANGE · today shape */
  getOpenCodeSettings: () => Promise<TodayResult<'opencode:settings:get'>>
  /** A-53 · `opencode:plugin:set` · invoke · CHANGE · today shape */
  setOpenCodePluginEnabled: (
    request: TodayRequest<'opencode:plugin:set'>
  ) => Promise<TodayResult<'opencode:plugin:set'>>
  /** A-54 · `opencode:password:set` · invoke · CHANGE · today shape */
  setOpenCodeServerPassword: (
    request: TodayRequest<'opencode:password:set'>
  ) => Promise<TodayResult<'opencode:password:set'>>
  /** A-55 · `opencode:password:clear` · invoke · CHANGE · today shape */
  clearOpenCodeServerPassword: () => Promise<TodayResult<'opencode:password:clear'>>
  /** A-56 · `launch-view:get` · invoke · KEEP · target shape */
  getLaunchView: () => Promise<TargetResult<'launch-view:get'>>
  /** A-57 · `launch-view:set` · send · KEEP · target shape */
  setLaunchView: (request: TargetRequest<'launch-view:set'>) => void
  /** A-P1 · `panel:visible:changed` · push · KEEP · target shape */
  onPanelVisibility: (
    listener: (payload: TargetResult<'panel:visible:changed'>) => void
  ) => () => void
  /** A-P2 · `mines:update` · push · RETIRE · target shape */
  onMinesUpdated: (listener: (payload: TargetResult<'mines:update'>) => void) => () => void
  /** A-P3 · `agent:launchFailed` · push · RETIRE · today shape */
  onLaunchFailed: (listener: (payload: TodayResult<'agent:launchFailed'>) => void) => () => void
  /** A-P4 · `dwarf:sendText:settled` · push · RETIRE · today shape */
  onDwarfSendSettled: (
    listener: (payload: TodayResult<'dwarf:sendText:settled'>) => void
  ) => () => void
  /** A-P5 · `panel:mine:show` · push · RETIRE · target shape */
  onShowMine: (listener: (payload: TargetResult<'panel:mine:show'>) => void) => () => void
  /** A-P6 · `typography:preferences:changed` · push · KEEP · target shape */
  onTypographyPreferences: (
    listener: (payload: TargetResult<'typography:preferences:changed'>) => void
  ) => () => void
  /** A-X1 · preload only · helper · KEEP · target shape */
  pathForDroppedFile: (
    file: TargetRequest<'pathForDroppedFile'>
  ) => TargetResult<'pathForDroppedFile'>
  /** §8 I-21 · `dwarf:setName` · invoke · RETIRE · today shape */
  setDwarfName: (request: TodayRequest<'dwarf:setName'>) => Promise<TodayResult<'dwarf:setName'>>
  /** §8 I-21 · `dwarf:resetName` · invoke · RETIRE · today shape */
  resetDwarfName: (
    request: TodayRequest<'dwarf:resetName'>
  ) => Promise<TodayResult<'dwarf:resetName'>>
  /** A-N30 · `diag:renderer:report` · send · NEW · target shape */
  reportRendererDiagnostic: (request: TargetRequest<'diag:renderer:report'>) => void
  /** A-N25 · `tray:stopEverything:requested` · push · NEW · target shape */
  onStopEverythingRequested: (
    listener: (payload: TargetResult<'tray:stopEverything:requested'>) => void
  ) => () => void
  /** A-N26 · `tray:stopEverything:confirm` · invoke · NEW · target shape */
  confirmStopEverything: (
    request: TargetRequest<'tray:stopEverything:confirm'>
  ) => Promise<TargetResult<'tray:stopEverything:confirm'>>
  /** A-N27 · `tray:stopEverything:cancel` · send · NEW · target shape */
  cancelStopEverything: (request: TargetRequest<'tray:stopEverything:cancel'>) => void
  /** A-N34 · `tray:stopEverything:request` · send · NEW · target shape */
  requestStopEverything: () => void
  /** A-N03 · `host:connection:get` · invoke · NEW · target shape */
  getHostConnection: () => Promise<TargetResult<'host:connection:get'>>
  /** A-N04 · `host:connection:changed` · push · NEW · target shape */
  onHostConnection: (
    listener: (payload: TargetResult<'host:connection:changed'>) => void
  ) => () => void
  /** A-N05 · `host:connection:retry` · invoke · NEW · target shape */
  retryHostConnection: () => Promise<TargetResult<'host:connection:retry'>>
  /** A-N33 · `host:connection:confirm-restart` · invoke · NEW · target shape */
  confirmHostRestart: () => Promise<TargetResult<'host:connection:confirm-restart'>>
  /** A-N17 · `ui:session:get` · invoke · NEW · target shape */
  getUiSession: () => Promise<TargetResult<'ui:session:get'>>
  /** A-N18 · `ui:session:patch` · send · NEW · target shape */
  patchUiSession: (request: TargetRequest<'ui:session:patch'>) => void
  /** A-N19 · `ui:session:changed` · push · NEW · target shape */
  onUiSessionChanged: (
    listener: (payload: TargetResult<'ui:session:changed'>) => void
  ) => () => void
  /** A-N20 · `ui:preferences:get` · invoke · NEW · target shape */
  getUiPreferences: (
    request: TargetRequest<'ui:preferences:get'>
  ) => Promise<TargetResult<'ui:preferences:get'>>
  /** A-N21 · `ui:preferences:set` · invoke · NEW · target shape */
  setUiPreference: (
    request: TargetRequest<'ui:preferences:set'>
  ) => Promise<TargetResult<'ui:preferences:set'>>
  /** A-N12 · `ui:preferences:reset` · push · NEW · target shape */
  onUiPreferencesReset: (
    listener: (payload: TargetResult<'ui:preferences:reset'>) => void
  ) => () => void
  /** A-N01 · `host:snapshot` · invoke · NEW · target shape */
  getHostSnapshot: (
    request: TargetRequest<'host:snapshot'>
  ) => Promise<TargetResult<'host:snapshot'>>
  /** A-N02 · `host:event` · push · NEW · target shape */
  onHostEvent: (listener: (payload: TargetResult<'host:event'>) => void) => () => void
  /** A-N16 · `mode:revealDwarfChat` · push · NEW · target shape */
  onRevealDwarfChat: (
    listener: (payload: TargetResult<'mode:revealDwarfChat'>) => void
  ) => () => void
  /** A-N31 · `claude:hooks:set` · invoke · NEW · target shape */
  setClaudeHooksEnabled: (
    request: TargetRequest<'claude:hooks:set'>
  ) => Promise<TargetResult<'claude:hooks:set'>>
}

const api: DwarfAiMinersApi = {
  hidePanel: () => sendOrDrop(() => ipcRenderer.send('panel:hide')),
  raisePanel: () => sendOrDrop(() => ipcRenderer.send('panel:raise')),
  getAlwaysOnTop: () => invokeOrReject(() => ipcRenderer.invoke('panel:getAlwaysOnTop')),
  setAlwaysOnTop: (request) =>
    invokeOrReject(() => ipcRenderer.invoke('panel:setAlwaysOnTop', request === true)),
  getPanelVisible: () => invokeOrReject(() => ipcRenderer.invoke('panel:visible:get')),
  getAudioPreferences: () => invokeOrReject(() => ipcRenderer.invoke('audio:preferences:get')),
  setAudioPreferences: (request) =>
    invokeOrReject(() => ipcRenderer.invoke('audio:preferences:set', request)),
  getPanelLayout: () => invokeOrReject(() => ipcRenderer.invoke('panel:layout:get')),
  setPanelLayout: (request) =>
    invokeOrReject(() =>
      ipcRenderer.invoke('panel:layout:set', {
        mineOpen: request?.mineOpen === true,
        dockOpen: request?.dockOpen === true,
        ...(request?.edge === 'left' || request?.edge === 'right' ? { edge: request.edge } : {})
      })
    ),
  getToggleShortcut: () => invokeOrReject(() => ipcRenderer.invoke('shortcut:get')),
  setToggleShortcut: (request) =>
    invokeOrReject(() => ipcRenderer.invoke('shortcut:set', textOf(request))),
  getMines: () => invokeOrReject(() => ipcRenderer.invoke('mines:get')),
  activateDwarf: (request) => invokeOrReject(() => ipcRenderer.invoke('dwarf:activate', request)),
  getDwarfFeed: (request) => invokeOrReject(() => ipcRenderer.invoke('dwarf:feed', request)),
  getDwarfFeedPage: (request) =>
    invokeOrReject(() => ipcRenderer.invoke('dwarf:feed:page', request)),
  setWatchedDwarf: (request) => sendOrDrop(() => ipcRenderer.send('panel:watchDwarfFeed', request)),
  refreshDwarfTelemetry: (request) =>
    sendOrDrop(() => ipcRenderer.send('dwarf:refreshTelemetry', request)),
  setDwarfTuning: (request) => invokeOrReject(() => ipcRenderer.invoke('dwarf:setTuning', request)),
  getMineHistory: (request) => invokeOrReject(() => ipcRenderer.invoke('mine:history', request)),
  openMinePath: (request) =>
    invokeOrReject(() =>
      ipcRenderer.invoke('mine:openPath', {
        mineId: textOf(request?.mineId),
        target: textOf(request?.target),
        ...(typeof request?.dwarfId === 'string' ? { dwarfId: request.dwarfId } : {})
      })
    ),
  openExternalLink: (request) =>
    invokeOrReject(() => ipcRenderer.invoke('shell:openExternalLink', textOf(request))),
  copyText: (request) =>
    invokeOrReject(() => ipcRenderer.invoke('shell:copyText', textOf(request))),
  sendDwarfText: (request) => invokeOrReject(() => ipcRenderer.invoke('dwarf:sendText', request)),
  chooseDwarfAttachments: () =>
    invokeOrReject(() => ipcRenderer.invoke('dwarf:attachments:choose')),
  describeDwarfAttachments: (request) =>
    invokeOrReject(() =>
      ipcRenderer.invoke(
        'dwarf:attachments:describe',
        (Array.isArray(request) ? request : []).map((path: unknown) => textOf(path))
      )
    ),
  kickDwarf: (request) => invokeOrReject(() => ipcRenderer.invoke('dwarf:kick', request)),
  retireDwarf: (request) => sendOrDrop(() => ipcRenderer.send('dwarf:retire', textOf(request))),
  getAppBuild: () => invokeOrReject(() => ipcRenderer.invoke('app:build')),
  getFeatureFlags: () => invokeOrReject(() => ipcRenderer.invoke('app:features')),
  declareMine: () => invokeOrReject(() => ipcRenderer.invoke('mine:declare')),
  declareMainProject: () => invokeOrReject(() => ipcRenderer.invoke('mine:declare-main')),
  undeclareMine: (request) =>
    invokeOrReject(() => ipcRenderer.invoke('mine:undeclare', textOf(request))),
  resetMetrics: (request) => invokeOrReject(() => ipcRenderer.invoke('metrics:reset', request)),
  queryProjects: (request) => invokeOrReject(() => ipcRenderer.invoke('projects:query', request)),
  launchAgent: (request) =>
    invokeOrReject(() =>
      ipcRenderer.invoke('agent:launch', {
        mineId: textOf(request?.mineId),
        provider: providerOf(request?.provider),
        prompt: textOf(request?.prompt),
        ...(typeof request?.model === 'string' ? { model: request.model } : {}),
        ...(typeof request?.effort === 'string' ? { effort: request.effort } : {}),
        ...(typeof request?.permissionMode === 'string'
          ? { permissionMode: request.permissionMode }
          : {}),
        ...(request?.routedByJev === true ? { routedByJev: true } : {})
      })
    ),
  listAgentProviders: () => invokeOrReject(() => ipcRenderer.invoke('agent:providers')),
  listAgentModels: () => invokeOrReject(() => ipcRenderer.invoke('agent:models')),
  launchHeldSession: (request) =>
    invokeOrReject(() =>
      ipcRenderer.invoke('agent:launchHeld', {
        mineId: textOf(request?.mineId),
        provider: providerOf(request?.provider),
        prompt: textOf(request?.prompt),
        ...(typeof request?.model === 'string' ? { model: request.model } : {}),
        ...(typeof request?.effort === 'string' ? { effort: request.effort } : {}),
        ...(typeof request?.permissionMode === 'string'
          ? { permissionMode: request.permissionMode }
          : {}),
        ...(request?.routedByJev === true ? { routedByJev: true } : {})
      })
    ),
  launchHostedProcess: (request) =>
    invokeOrReject(() =>
      ipcRenderer.invoke('agent:launchHosted', {
        mineId: textOf(request?.mineId),
        command: textOf(request?.command),
        prompt: textOf(request?.prompt)
      })
    ),
  answerDwarfQuestion: (request) =>
    invokeOrReject(() => ipcRenderer.invoke('agent:answerQuestion', questionAnswerOf(request))),
  answerDwarfPermission: (request) =>
    invokeOrReject(() =>
      ipcRenderer.invoke('agent:answerPermission', {
        dwarfId: textOf(request?.dwarfId),
        toolUseId: textOf(request?.toolUseId),
        decision: textOf(request?.decision)
      })
    ),
  getNotificationsEnabled: () =>
    invokeOrReject(() => ipcRenderer.invoke('notifications:enabled:get')),
  setNotificationsEnabled: (request) =>
    invokeOrReject(() => ipcRenderer.invoke('notifications:enabled:set', request === true)),
  reportVisibleMines: (request) =>
    sendOrDrop(() => ipcRenderer.send('presence:visibleMines', request)),
  getTypographyPreferences: () =>
    invokeOrReject(() => ipcRenderer.invoke('typography:preferences:get')),
  setTypographyPreferences: (request) =>
    invokeOrReject(() => ipcRenderer.invoke('typography:preferences:set', request)),
  getJevSettings: () => invokeOrReject(() => ipcRenderer.invoke('jev:settings:get')),
  setJevApiKey: (request) => invokeOrReject(() => ipcRenderer.invoke('jev:apiKey:set', request)),
  clearJevApiKey: () => invokeOrReject(() => ipcRenderer.invoke('jev:apiKey:clear')),
  routeJevLaunch: (request) => invokeOrReject(() => ipcRenderer.invoke('jev:route', request)),
  setJevPreferences: (request) =>
    invokeOrReject(() => ipcRenderer.invoke('jev:preferences:set', request)),
  getOpenCodeSettings: () => invokeOrReject(() => ipcRenderer.invoke('opencode:settings:get')),
  setOpenCodePluginEnabled: (request) =>
    invokeOrReject(() => ipcRenderer.invoke('opencode:plugin:set', request === true)),
  setOpenCodeServerPassword: (request) =>
    invokeOrReject(() => ipcRenderer.invoke('opencode:password:set', request)),
  clearOpenCodeServerPassword: () =>
    invokeOrReject(() => ipcRenderer.invoke('opencode:password:clear')),
  getLaunchView: () => invokeOrReject(() => ipcRenderer.invoke('launch-view:get')),
  setLaunchView: (request) => sendOrDrop(() => ipcRenderer.send('launch-view:set', request)),
  onPanelVisibility: (listener) => {
    const wrapped = (_event: IpcRendererEvent, payload: unknown): void => {
      listener(payload === true)
    }
    ipcRenderer.on('panel:visible:changed', wrapped)
    return () => ipcRenderer.removeListener('panel:visible:changed', wrapped)
  },
  onMinesUpdated: (listener) => {
    const wrapped = (_event: IpcRendererEvent, payload: unknown): void => {
      listener(payload as TargetResult<'mines:update'>)
    }
    ipcRenderer.on('mines:update', wrapped)
    return () => ipcRenderer.removeListener('mines:update', wrapped)
  },
  onLaunchFailed: (listener) => {
    const wrapped = (_event: IpcRendererEvent, payload: unknown): void => {
      listener(payload as TodayResult<'agent:launchFailed'>)
    }
    ipcRenderer.on('agent:launchFailed', wrapped)
    return () => ipcRenderer.removeListener('agent:launchFailed', wrapped)
  },
  onDwarfSendSettled: (listener) => {
    const wrapped = (_event: IpcRendererEvent, payload: unknown): void => {
      listener(payload as TodayResult<'dwarf:sendText:settled'>)
    }
    ipcRenderer.on('dwarf:sendText:settled', wrapped)
    return () => ipcRenderer.removeListener('dwarf:sendText:settled', wrapped)
  },
  onShowMine: (listener) => {
    const wrapped = (_event: IpcRendererEvent, payload: unknown): void => {
      listener(payload as TargetResult<'panel:mine:show'>)
    }
    ipcRenderer.on('panel:mine:show', wrapped)
    return () => ipcRenderer.removeListener('panel:mine:show', wrapped)
  },
  onTypographyPreferences: (listener) => {
    const wrapped = (_event: IpcRendererEvent, payload: unknown): void => {
      listener(payload as TargetResult<'typography:preferences:changed'>)
    }
    ipcRenderer.on('typography:preferences:changed', wrapped)
    return () => ipcRenderer.removeListener('typography:preferences:changed', wrapped)
  },
  pathForDroppedFile: (file) => {
    try {
      return webUtils.getPathForFile(file)
    } catch {
      return ''
    }
  },
  setDwarfName: (request) =>
    invokeOrReject(() =>
      ipcRenderer.invoke('dwarf:setName', {
        dwarfId: textOf(request?.dwarfId),
        ...(typeof request?.name === 'string' ? { name: request.name } : {})
      })
    ),
  resetDwarfName: (request) =>
    invokeOrReject(() => ipcRenderer.invoke('dwarf:resetName', textOf(request))),
  reportRendererDiagnostic: (request) =>
    sendOrDrop(() => ipcRenderer.send('diag:renderer:report', request)),
  onStopEverythingRequested: (listener) => {
    const wrapped = (_event: IpcRendererEvent, payload: unknown): void => {
      listener(payload as TargetResult<'tray:stopEverything:requested'>)
    }
    ipcRenderer.on('tray:stopEverything:requested', wrapped)
    return () => ipcRenderer.removeListener('tray:stopEverything:requested', wrapped)
  },
  confirmStopEverything: (request) =>
    invokeOrReject(() => ipcRenderer.invoke('tray:stopEverything:confirm', request)),
  cancelStopEverything: (request) =>
    sendOrDrop(() => ipcRenderer.send('tray:stopEverything:cancel', request)),
  requestStopEverything: () => sendOrDrop(() => ipcRenderer.send('tray:stopEverything:request')),
  getHostConnection: () => invokeOrReject(() => ipcRenderer.invoke('host:connection:get')),
  onHostConnection: (listener) => {
    const wrapped = (_event: IpcRendererEvent, payload: unknown): void => {
      listener(payload as TargetResult<'host:connection:changed'>)
    }
    ipcRenderer.on('host:connection:changed', wrapped)
    return () => ipcRenderer.removeListener('host:connection:changed', wrapped)
  },
  retryHostConnection: () => invokeOrReject(() => ipcRenderer.invoke('host:connection:retry')),
  confirmHostRestart: () =>
    invokeOrReject(() => ipcRenderer.invoke('host:connection:confirm-restart')),
  getUiSession: () => invokeOrReject(() => ipcRenderer.invoke('ui:session:get')),
  patchUiSession: (request) => sendOrDrop(() => ipcRenderer.send('ui:session:patch', request)),
  onUiSessionChanged: (listener) => {
    const wrapped = (_event: IpcRendererEvent, payload: unknown): void => {
      listener(payload as TargetResult<'ui:session:changed'>)
    }
    ipcRenderer.on('ui:session:changed', wrapped)
    return () => ipcRenderer.removeListener('ui:session:changed', wrapped)
  },
  getUiPreferences: (request) =>
    invokeOrReject(() => ipcRenderer.invoke('ui:preferences:get', request)),
  setUiPreference: (request) =>
    invokeOrReject(() => ipcRenderer.invoke('ui:preferences:set', request)),
  onUiPreferencesReset: (listener) => {
    const wrapped = (_event: IpcRendererEvent, payload: unknown): void => {
      listener(payload as TargetResult<'ui:preferences:reset'>)
    }
    ipcRenderer.on('ui:preferences:reset', wrapped)
    return () => ipcRenderer.removeListener('ui:preferences:reset', wrapped)
  },
  getHostSnapshot: (request) => invokeOrReject(() => ipcRenderer.invoke('host:snapshot', request)),
  onHostEvent: (listener) => {
    const wrapped = (_event: IpcRendererEvent, payload: unknown): void => {
      listener(payload as TargetResult<'host:event'>)
    }
    ipcRenderer.on('host:event', wrapped)
    return () => ipcRenderer.removeListener('host:event', wrapped)
  },
  onRevealDwarfChat: (listener) => {
    const wrapped = (_event: IpcRendererEvent, payload: unknown): void => {
      listener(payload as TargetResult<'mode:revealDwarfChat'>)
    }
    ipcRenderer.on('mode:revealDwarfChat', wrapped)
    return () => ipcRenderer.removeListener('mode:revealDwarfChat', wrapped)
  },
  setClaudeHooksEnabled: (request) =>
    invokeOrReject(() => ipcRenderer.invoke('claude:hooks:set', request))
}

contextBridge.exposeInMainWorld('api', api)
