// GENERATED by `pnpm ipc:generate` (scripts/ipc/generate-window-api.mjs) — do not edit by hand (22 §5).
// The preload: `window.api`, one member per registry row (14 §2.1; ADR-033 item 6; ADR-019 item 1).
// Source: the channel registry (src/contracts/ipc) and the route table's shapes (src/ui-main/ipc/routes.ts).
//
// Each member speaks on its row's wire with the types of the shape its route uses in this release; it coerces for
// ergonomics and never throws (a value it cannot coerce is passed on for main to refuse, 14 §1.4). Built as one
// CommonJS script whose only runtime import is `electron`, so it loads in a sandboxed renderer (S-019-1).
import { contextBridge, ipcRenderer, webUtils, type IpcRendererEvent } from 'electron'
import type { z } from 'zod'
import type { CHANNELS, ChannelKey } from '@dwarfai/contracts'
import type { TODAY } from '../contracts/ipc/todayShapes'

/** A request as the renderer hands it over: the preload never mutates it, so an array may be readonly. */
type Accepted<T> = T extends readonly (infer I)[]
  ? readonly Accepted<I>[]
  : T extends File
    ? T
    : T extends object
      ? { [P in keyof T]: Accepted<T[P]> }
      : T
/** A row's today shape (21 §1 item 2a): its TODAY_SHAPES entry, or its registry entry for a KEEP row. */
type TodayRow<K extends ChannelKey> = K extends keyof typeof TODAY
  ? (typeof TODAY)[K]
  : (typeof CHANNELS)[K]
type TodayRequest<K extends ChannelKey> = Accepted<z.input<TodayRow<K>['request']>>
type TodayResult<K extends ChannelKey> = z.output<TodayRow<K>['response']>

/** An id or a text as a string, or '' which main refuses. */
function textOf(value: unknown): string {
  return typeof value === 'string' ? value : ''
}

/** Today's provider names (the today launch request's enum); an unknown one crosses as '', never a default. */
const PROVIDERS: readonly unknown[] = ['claude', 'codex', 'antigravity', 'opencode']
function providerOf(value: unknown): string {
  return typeof value === 'string' && PROVIDERS.includes(value) ? value : ''
}

/**
 * The one act a tuning request names. An unrecognised kind crosses as a shape main refuses, never as either real
 * act: this changes a running session.
 */
function tuningChangeOf(change: unknown): {
  kind: string
  model?: string
  effort?: string
  value?: string
} {
  const record =
    typeof change === 'object' && change !== null ? (change as Record<string, unknown>) : {}
  if (record.kind === 'model' && typeof record.model === 'string')
    return { kind: 'model', model: record.model }
  if (record.kind === 'effort' && typeof record.effort === 'string') {
    return { kind: 'effort', effort: record.effort }
  }
  return { kind: '', value: '' }
}

/**
 * An answer rebuilt from string pairs only. The person's own words (`text`) cross alone, never beside a record;
 * a non-string value is dropped, so main refuses an answer that names no option.
 */
function questionAnswerOf(request: unknown): Record<string, unknown> {
  const record =
    typeof request === 'object' && request !== null ? (request as Record<string, unknown>) : {}
  const address = { dwarfId: textOf(record.dwarfId), toolUseId: textOf(record.toolUseId) }
  if (record.text !== undefined) {
    return { ...address, ...(typeof record.text === 'string' ? { text: record.text } : {}) }
  }
  const answers = stringPairsOf(record.answers)
  const ownWords = stringPairsOf(record.ownWords)
  return { ...address, answers, ...(Object.keys(ownWords).length === 0 ? {} : { ownWords }) }
}
function stringPairsOf(value: unknown): Record<string, string> {
  const pairs: Record<string, string> = {}
  if (typeof value !== 'object' || value === null) return pairs
  for (const [key, entry] of Object.entries(value))
    if (typeof entry === 'string') pairs[key] = entry
  return pairs
}

/** API surface exposed to the renderer as `window.api`. */
export interface DwarfAiMinersApi {
  /** A-01 · `panel:hide` · send · KEEP · today shape */
  hidePanel: () => void
  /** A-02 · `panel:raise` · send · KEEP · today shape */
  raisePanel: () => void
  /** A-03 · `panel:getAlwaysOnTop` · invoke · KEEP · today shape */
  getAlwaysOnTop: () => Promise<TodayResult<'panel:getAlwaysOnTop'>>
  /** A-04 · `panel:setAlwaysOnTop` · invoke · KEEP · today shape */
  setAlwaysOnTop: (
    request: TodayRequest<'panel:setAlwaysOnTop'>
  ) => Promise<TodayResult<'panel:setAlwaysOnTop'>>
  /** A-05 · `panel:visible:get` · invoke · KEEP · today shape */
  getPanelVisible: () => Promise<TodayResult<'panel:visible:get'>>
  /** A-06 · `audio:preferences:get` · invoke · KEEP · today shape */
  getAudioPreferences: () => Promise<TodayResult<'audio:preferences:get'>>
  /** A-07 · `audio:preferences:set` · invoke · KEEP · today shape */
  setAudioPreferences: (
    request: TodayRequest<'audio:preferences:set'>
  ) => Promise<TodayResult<'audio:preferences:set'>>
  /** A-08 · `panel:layout:get` · invoke · KEEP · today shape */
  getPanelLayout: () => Promise<TodayResult<'panel:layout:get'>>
  /** A-09 · `panel:layout:set` · invoke · KEEP · today shape */
  setPanelLayout: (
    request: TodayRequest<'panel:layout:set'>
  ) => Promise<TodayResult<'panel:layout:set'>>
  /** A-10 · `shortcut:get` · invoke · KEEP · today shape */
  getToggleShortcut: () => Promise<TodayResult<'shortcut:get'>>
  /** A-11 · `shortcut:set` · invoke · KEEP · today shape */
  setToggleShortcut: (request: TodayRequest<'shortcut:set'>) => Promise<TodayResult<'shortcut:set'>>
  /** A-12 · `mines:get` · invoke · RETIRE · today shape */
  getMines: () => Promise<TodayResult<'mines:get'>>
  /** A-13 · `dwarf:activate` · invoke · CHANGE · today shape */
  activateDwarf: (request: TodayRequest<'dwarf:activate'>) => Promise<TodayResult<'dwarf:activate'>>
  /** A-14 · `dwarf:feed` · invoke · RETIRE · today shape */
  getDwarfFeed: (request: TodayRequest<'dwarf:feed'>) => Promise<TodayResult<'dwarf:feed'>>
  /** A-15 · `dwarf:feed:page` · invoke · CHANGE · today shape */
  getDwarfFeedPage: (
    request: TodayRequest<'dwarf:feed:page'>
  ) => Promise<TodayResult<'dwarf:feed:page'>>
  /** A-16 · `panel:watchDwarfFeed` · send · RETIRE · today shape */
  setWatchedDwarf: (request: TodayRequest<'panel:watchDwarfFeed'>) => void
  /** A-17 · `dwarf:refreshTelemetry` · send · RETIRE · today shape */
  refreshDwarfTelemetry: (request: TodayRequest<'dwarf:refreshTelemetry'>) => void
  /** A-18 · `dwarf:setTuning` · invoke · RETIRE · today shape */
  setDwarfTuning: (
    request: TodayRequest<'dwarf:setTuning'>
  ) => Promise<TodayResult<'dwarf:setTuning'>>
  /** A-19 · `mine:history` · invoke · CHANGE · today shape */
  getMineHistory: (request: TodayRequest<'mine:history'>) => Promise<TodayResult<'mine:history'>>
  /** A-20 · `mine:openPath` · invoke · KEEP · today shape */
  openMinePath: (request: TodayRequest<'mine:openPath'>) => Promise<TodayResult<'mine:openPath'>>
  /** A-21 · `shell:openExternalLink` · invoke · KEEP · today shape */
  openExternalLink: (
    request: TodayRequest<'shell:openExternalLink'>
  ) => Promise<TodayResult<'shell:openExternalLink'>>
  /** A-22 · `shell:copyText` · invoke · KEEP · today shape */
  copyText: (request: TodayRequest<'shell:copyText'>) => Promise<TodayResult<'shell:copyText'>>
  /** A-23 · `dwarf:sendText` · invoke · CHANGE · today shape */
  sendDwarfText: (request: TodayRequest<'dwarf:sendText'>) => Promise<TodayResult<'dwarf:sendText'>>
  /** A-24 · `dwarf:attachments:choose` · invoke · KEEP · today shape */
  chooseDwarfAttachments: () => Promise<TodayResult<'dwarf:attachments:choose'>>
  /** A-25 · `dwarf:attachments:describe` · invoke · KEEP · today shape */
  describeDwarfAttachments: (
    request: TodayRequest<'dwarf:attachments:describe'>
  ) => Promise<TodayResult<'dwarf:attachments:describe'>>
  /** A-26 · `dwarf:kick` · invoke · RETIRE · today shape */
  kickDwarf: (request: TodayRequest<'dwarf:kick'>) => Promise<TodayResult<'dwarf:kick'>>
  /** A-27 · `dwarf:retire` · send · RETIRE · today shape */
  retireDwarf: (request: TodayRequest<'dwarf:retire'>) => void
  /** A-28 · `app:build` · invoke · KEEP · today shape */
  getAppBuild: () => Promise<TodayResult<'app:build'>>
  /** A-29 · `app:features` · invoke · KEEP · today shape */
  getFeatureFlags: () => Promise<TodayResult<'app:features'>>
  /** A-30 · `mine:declare` · invoke · KEEP · today shape */
  declareMine: () => Promise<TodayResult<'mine:declare'>>
  /** A-31 · `mine:declare-main` · invoke · KEEP · today shape */
  declareMainProject: () => Promise<TodayResult<'mine:declare-main'>>
  /** A-32 · `mine:undeclare` · invoke · KEEP · today shape */
  undeclareMine: (request: TodayRequest<'mine:undeclare'>) => Promise<TodayResult<'mine:undeclare'>>
  /** A-33 · `metrics:reset` · invoke · CHANGE · today shape */
  resetMetrics: () => Promise<TodayResult<'metrics:reset'>>
  /** A-34 · `projects:query` · invoke · KEEP · today shape */
  queryProjects: (request: TodayRequest<'projects:query'>) => Promise<TodayResult<'projects:query'>>
  /** A-35 · `agent:launch` · invoke · CHANGE · today shape */
  launchAgent: (request: TodayRequest<'agent:launch'>) => Promise<TodayResult<'agent:launch'>>
  /** A-36 · `agent:providers` · invoke · CHANGE · today shape */
  listAgentProviders: () => Promise<TodayResult<'agent:providers'>>
  /** A-37 · `agent:models` · invoke · RETIRE · today shape */
  listAgentModels: () => Promise<TodayResult<'agent:models'>>
  /** A-38 · `agent:launchHeld` · invoke · RETIRE · today shape */
  launchHeldSession: (
    request: TodayRequest<'agent:launchHeld'>
  ) => Promise<TodayResult<'agent:launchHeld'>>
  /** A-39 · `agent:launchHosted` · invoke · CHANGE · today shape */
  launchHostedProcess: (
    request: TodayRequest<'agent:launchHosted'>
  ) => Promise<TodayResult<'agent:launchHosted'>>
  /** A-40 · `agent:answerQuestion` · invoke · CHANGE · today shape */
  answerDwarfQuestion: (
    request: TodayRequest<'agent:answerQuestion'>
  ) => Promise<TodayResult<'agent:answerQuestion'>>
  /** A-41 · `agent:answerPermission` · invoke · CHANGE · today shape */
  answerDwarfPermission: (
    request: TodayRequest<'agent:answerPermission'>
  ) => Promise<TodayResult<'agent:answerPermission'>>
  /** A-42 · `notifications:enabled:get` · invoke · KEEP · today shape */
  getNotificationsEnabled: () => Promise<TodayResult<'notifications:enabled:get'>>
  /** A-43 · `notifications:enabled:set` · invoke · KEEP · today shape */
  setNotificationsEnabled: (
    request: TodayRequest<'notifications:enabled:set'>
  ) => Promise<TodayResult<'notifications:enabled:set'>>
  /** A-44 · `panel:openMine` · send · CHANGE · today shape */
  setOpenMine: (request: TodayRequest<'presence:visibleMines'>) => void
  /** A-45 · `typography:preferences:get` · invoke · KEEP · today shape */
  getTypographyPreferences: () => Promise<TodayResult<'typography:preferences:get'>>
  /** A-46 · `typography:preferences:set` · invoke · KEEP · today shape */
  setTypographyPreferences: (
    request: TodayRequest<'typography:preferences:set'>
  ) => Promise<TodayResult<'typography:preferences:set'>>
  /** A-47 · `jev:settings:get` · invoke · KEEP · today shape */
  getJevSettings: () => Promise<TodayResult<'jev:settings:get'>>
  /** A-48 · `jev:apiKey:set` · invoke · KEEP · today shape */
  setJevApiKey: (request: TodayRequest<'jev:apiKey:set'>) => Promise<TodayResult<'jev:apiKey:set'>>
  /** A-49 · `jev:apiKey:clear` · invoke · KEEP · today shape */
  clearJevApiKey: () => Promise<TodayResult<'jev:apiKey:clear'>>
  /** A-50 · `jev:route` · invoke · CHANGE · today shape */
  routeJevLaunch: (request: TodayRequest<'jev:route'>) => Promise<TodayResult<'jev:route'>>
  /** A-51 · `jev:preferences:set` · invoke · KEEP · today shape */
  setJevPreferences: (
    request: TodayRequest<'jev:preferences:set'>
  ) => Promise<TodayResult<'jev:preferences:set'>>
  /** A-52 · `opencode:settings:get` · invoke · CHANGE · today shape */
  getOpenCodeSettings: () => Promise<TodayResult<'opencode:settings:get'>>
  /** A-53 · `opencode:plugin:set` · invoke · CHANGE · today shape */
  setOpenCodePluginEnabled: (
    request: TodayRequest<'opencode:plugin:set'>
  ) => Promise<TodayResult<'opencode:plugin:set'>>
  /** A-54 · `opencode:password:set` · invoke · CHANGE · today shape */
  setOpenCodeServerPassword: (
    request: TodayRequest<'opencode:password:set'>
  ) => Promise<TodayResult<'opencode:password:set'>>
  /** A-55 · `opencode:password:clear` · invoke · CHANGE · today shape */
  clearOpenCodeServerPassword: () => Promise<TodayResult<'opencode:password:clear'>>
  /** A-56 · `launch-view:get` · invoke · KEEP · today shape */
  getLaunchView: () => Promise<TodayResult<'launch-view:get'>>
  /** A-57 · `launch-view:set` · send · KEEP · today shape */
  setLaunchView: (request: TodayRequest<'launch-view:set'>) => void
  /** A-P1 · `panel:visible:changed` · push · KEEP · today shape */
  onPanelVisibility: (
    listener: (payload: TodayResult<'panel:visible:changed'>) => void
  ) => () => void
  /** A-P2 · `mines:update` · push · RETIRE · today shape */
  onMinesUpdated: (listener: (payload: TodayResult<'mines:update'>) => void) => () => void
  /** A-P3 · `agent:launchFailed` · push · RETIRE · today shape */
  onLaunchFailed: (listener: (payload: TodayResult<'agent:launchFailed'>) => void) => () => void
  /** A-P4 · `dwarf:sendText:settled` · push · RETIRE · today shape */
  onDwarfSendSettled: (
    listener: (payload: TodayResult<'dwarf:sendText:settled'>) => void
  ) => () => void
  /** A-P5 · `panel:mine:show` · push · RETIRE · today shape */
  onShowMine: (listener: (payload: TodayResult<'panel:mine:show'>) => void) => () => void
  /** A-P6 · `typography:preferences:changed` · push · KEEP · today shape */
  onTypographyPreferences: (
    listener: (payload: TodayResult<'typography:preferences:changed'>) => void
  ) => () => void
  /** A-X1 · preload only · helper · KEEP · today shape */
  pathForDroppedFile: (
    file: TodayRequest<'pathForDroppedFile'>
  ) => TodayResult<'pathForDroppedFile'>
  /** §8 I-21 · `dwarf:setName` · invoke · RETIRE · today shape */
  setDwarfName: (request: TodayRequest<'dwarf:setName'>) => Promise<TodayResult<'dwarf:setName'>>
  /** §8 I-21 · `dwarf:resetName` · invoke · RETIRE · today shape */
  resetDwarfName: (
    request: TodayRequest<'dwarf:resetName'>
  ) => Promise<TodayResult<'dwarf:resetName'>>
}

const api: DwarfAiMinersApi = {
  hidePanel: () => ipcRenderer.send('panel:hide'),
  raisePanel: () => ipcRenderer.send('panel:raise'),
  getAlwaysOnTop: () => ipcRenderer.invoke('panel:getAlwaysOnTop'),
  setAlwaysOnTop: (request) => ipcRenderer.invoke('panel:setAlwaysOnTop', request === true),
  getPanelVisible: () => ipcRenderer.invoke('panel:visible:get'),
  getAudioPreferences: () => ipcRenderer.invoke('audio:preferences:get'),
  setAudioPreferences: (request) => ipcRenderer.invoke('audio:preferences:set', request),
  getPanelLayout: () => ipcRenderer.invoke('panel:layout:get'),
  setPanelLayout: (request) =>
    ipcRenderer.invoke('panel:layout:set', {
      mineOpen: request?.mineOpen === true,
      dockOpen: request?.dockOpen === true,
      ...(request?.edge === 'left' || request?.edge === 'right' ? { edge: request.edge } : {})
    }),
  getToggleShortcut: () => ipcRenderer.invoke('shortcut:get'),
  setToggleShortcut: (request) => ipcRenderer.invoke('shortcut:set', textOf(request)),
  getMines: () => ipcRenderer.invoke('mines:get'),
  activateDwarf: (request) => ipcRenderer.invoke('dwarf:activate', request),
  getDwarfFeed: (request) => ipcRenderer.invoke('dwarf:feed', textOf(request)),
  getDwarfFeedPage: (request) =>
    ipcRenderer.invoke('dwarf:feed:page', {
      dwarfId: textOf(request?.dwarfId),
      before: { timestamp: textOf(request?.before?.timestamp), text: textOf(request?.before?.text) }
    }),
  setWatchedDwarf: (request) =>
    ipcRenderer.send('panel:watchDwarfFeed', typeof request === 'string' ? request : null),
  refreshDwarfTelemetry: (request) => ipcRenderer.send('dwarf:refreshTelemetry', textOf(request)),
  setDwarfTuning: (request) =>
    ipcRenderer.invoke('dwarf:setTuning', {
      dwarfId: textOf(request?.dwarfId),
      change: tuningChangeOf(request?.change)
    }),
  getMineHistory: (request) => ipcRenderer.invoke('mine:history', textOf(request)),
  openMinePath: (request) =>
    ipcRenderer.invoke('mine:openPath', {
      mineId: textOf(request?.mineId),
      target: textOf(request?.target),
      ...(typeof request?.dwarfId === 'string' ? { dwarfId: request.dwarfId } : {})
    }),
  openExternalLink: (request) => ipcRenderer.invoke('shell:openExternalLink', textOf(request)),
  copyText: (request) => ipcRenderer.invoke('shell:copyText', textOf(request)),
  sendDwarfText: (request) => ipcRenderer.invoke('dwarf:sendText', request),
  chooseDwarfAttachments: () => ipcRenderer.invoke('dwarf:attachments:choose'),
  describeDwarfAttachments: (request) =>
    ipcRenderer.invoke(
      'dwarf:attachments:describe',
      (Array.isArray(request) ? request : []).map((path: unknown) => textOf(path))
    ),
  kickDwarf: (request) => ipcRenderer.invoke('dwarf:kick', request),
  retireDwarf: (request) => ipcRenderer.send('dwarf:retire', textOf(request)),
  getAppBuild: () => ipcRenderer.invoke('app:build'),
  getFeatureFlags: () => ipcRenderer.invoke('app:features'),
  declareMine: () => ipcRenderer.invoke('mine:declare'),
  declareMainProject: () => ipcRenderer.invoke('mine:declare-main'),
  undeclareMine: (request) => ipcRenderer.invoke('mine:undeclare', textOf(request)),
  resetMetrics: () => ipcRenderer.invoke('metrics:reset'),
  queryProjects: (request) => ipcRenderer.invoke('projects:query', request),
  launchAgent: (request) =>
    ipcRenderer.invoke('agent:launch', {
      mineId: textOf(request?.mineId),
      provider: providerOf(request?.provider),
      prompt: textOf(request?.prompt),
      ...(typeof request?.model === 'string' ? { model: request.model } : {}),
      ...(typeof request?.effort === 'string' ? { effort: request.effort } : {}),
      ...(typeof request?.permissionMode === 'string'
        ? { permissionMode: request.permissionMode }
        : {}),
      ...(request?.routedByJev === true ? { routedByJev: true } : {})
    }),
  listAgentProviders: () => ipcRenderer.invoke('agent:providers'),
  listAgentModels: () => ipcRenderer.invoke('agent:models'),
  launchHeldSession: (request) =>
    ipcRenderer.invoke('agent:launchHeld', {
      mineId: textOf(request?.mineId),
      provider: providerOf(request?.provider),
      prompt: textOf(request?.prompt),
      ...(typeof request?.model === 'string' ? { model: request.model } : {}),
      ...(typeof request?.effort === 'string' ? { effort: request.effort } : {}),
      ...(typeof request?.permissionMode === 'string'
        ? { permissionMode: request.permissionMode }
        : {}),
      ...(request?.routedByJev === true ? { routedByJev: true } : {})
    }),
  launchHostedProcess: (request) =>
    ipcRenderer.invoke('agent:launchHosted', {
      mineId: textOf(request?.mineId),
      command: textOf(request?.command),
      prompt: textOf(request?.prompt)
    }),
  answerDwarfQuestion: (request) =>
    ipcRenderer.invoke('agent:answerQuestion', questionAnswerOf(request)),
  answerDwarfPermission: (request) =>
    ipcRenderer.invoke('agent:answerPermission', {
      dwarfId: textOf(request?.dwarfId),
      toolUseId: textOf(request?.toolUseId),
      decision: textOf(request?.decision)
    }),
  getNotificationsEnabled: () => ipcRenderer.invoke('notifications:enabled:get'),
  setNotificationsEnabled: (request) =>
    ipcRenderer.invoke('notifications:enabled:set', request === true),
  setOpenMine: (request) =>
    ipcRenderer.send('panel:openMine', typeof request === 'string' ? request : null),
  getTypographyPreferences: () => ipcRenderer.invoke('typography:preferences:get'),
  setTypographyPreferences: (request) => ipcRenderer.invoke('typography:preferences:set', request),
  getJevSettings: () => ipcRenderer.invoke('jev:settings:get'),
  setJevApiKey: (request) => ipcRenderer.invoke('jev:apiKey:set', request),
  clearJevApiKey: () => ipcRenderer.invoke('jev:apiKey:clear'),
  routeJevLaunch: (request) => ipcRenderer.invoke('jev:route', request),
  setJevPreferences: (request) => ipcRenderer.invoke('jev:preferences:set', request),
  getOpenCodeSettings: () => ipcRenderer.invoke('opencode:settings:get'),
  setOpenCodePluginEnabled: (request) =>
    ipcRenderer.invoke('opencode:plugin:set', request === true),
  setOpenCodeServerPassword: (request) => ipcRenderer.invoke('opencode:password:set', request),
  clearOpenCodeServerPassword: () => ipcRenderer.invoke('opencode:password:clear'),
  getLaunchView: () => ipcRenderer.invoke('launch-view:get'),
  setLaunchView: (request) => ipcRenderer.send('launch-view:set', request),
  onPanelVisibility: (listener) => {
    const wrapped = (_event: IpcRendererEvent, payload: unknown): void => {
      listener(payload === true)
    }
    ipcRenderer.on('panel:visible:changed', wrapped)
    return () => ipcRenderer.removeListener('panel:visible:changed', wrapped)
  },
  onMinesUpdated: (listener) => {
    const wrapped = (_event: IpcRendererEvent, payload: unknown): void => {
      listener(payload as TodayResult<'mines:update'>)
    }
    ipcRenderer.on('mines:update', wrapped)
    return () => ipcRenderer.removeListener('mines:update', wrapped)
  },
  onLaunchFailed: (listener) => {
    const wrapped = (_event: IpcRendererEvent, payload: unknown): void => {
      listener(payload as TodayResult<'agent:launchFailed'>)
    }
    ipcRenderer.on('agent:launchFailed', wrapped)
    return () => ipcRenderer.removeListener('agent:launchFailed', wrapped)
  },
  onDwarfSendSettled: (listener) => {
    const wrapped = (_event: IpcRendererEvent, payload: unknown): void => {
      listener(payload as TodayResult<'dwarf:sendText:settled'>)
    }
    ipcRenderer.on('dwarf:sendText:settled', wrapped)
    return () => ipcRenderer.removeListener('dwarf:sendText:settled', wrapped)
  },
  onShowMine: (listener) => {
    const wrapped = (_event: IpcRendererEvent, payload: unknown): void => {
      if (typeof payload === 'string' && payload !== '') listener(payload)
    }
    ipcRenderer.on('panel:mine:show', wrapped)
    return () => ipcRenderer.removeListener('panel:mine:show', wrapped)
  },
  onTypographyPreferences: (listener) => {
    const wrapped = (_event: IpcRendererEvent, payload: unknown): void => {
      listener(payload as TodayResult<'typography:preferences:changed'>)
    }
    ipcRenderer.on('typography:preferences:changed', wrapped)
    return () => ipcRenderer.removeListener('typography:preferences:changed', wrapped)
  },
  pathForDroppedFile: (file) => {
    try {
      return webUtils.getPathForFile(file)
    } catch {
      return ''
    }
  },
  setDwarfName: (request) =>
    ipcRenderer.invoke('dwarf:setName', {
      dwarfId: textOf(request?.dwarfId),
      ...(typeof request?.name === 'string' ? { name: request.name } : {})
    }),
  resetDwarfName: (request) => ipcRenderer.invoke('dwarf:resetName', textOf(request))
}

contextBridge.exposeInMainWorld('api', api)
