import { Menu, Tray, app, nativeImage } from 'electron'
import {
  disable as disableAutostart,
  enable as enableAutostart,
  isEnabled as isAutostartEnabled
} from './autostart'
import { applyHookToggle, HOOKS_MENU_LABEL, type HookToggleTarget } from './hooks/hookChannel'
import { autostartMenuLabel } from './platform/autostartEntries'
import { currentPlatform } from './platform/platform'
import { resolveResourcePath } from './resourcePaths'
import { togglePanel } from './window'

let tray: Tray | null = null

/**
 * The optional hook channel, when the app wired one up. Null keeps the menu
 * item out entirely, so nothing about this feature can appear in a build or a
 * test that never constructed it.
 */
let hooks: HookToggleTarget | null = null

/**
 * Electron's nativeImage automatically picks up a "@2x" sibling for HiDPI
 * displays when the base image is loaded from a file path, so only the
 * 16x16 base name is referenced here — see resources/tray-icon.png and
 * tray-icon@2x.png, both generated by `pnpm icons` from the same painted
 * mound art as the installer and window icons.
 */
function trayIconPath(): string {
  return resolveResourcePath('tray-icon.png', {
    isPackaged: app.isPackaged,
    resourcesPath: process.resourcesPath,
    appPath: app.getAppPath()
  })
}

export interface TrayOptions {
  /** Opt-in push channel; omitted when the app did not build one. */
  hooks?: HookToggleTarget
}

export async function createTray(options: TrayOptions = {}): Promise<Tray> {
  hooks = options.hooks ?? null
  const icon = nativeImage.createFromPath(trayIconPath())
  tray = new Tray(icon)
  tray.setToolTip('DwarfAI-Miners')
  tray.on('click', () => togglePanel())
  await refreshTrayMenu()
  return tray
}

/**
 * The instant-updates checkbox, or nothing when no channel was wired up.
 *
 * Default OFF and never enabled on the user's behalf: turning it on writes
 * hook entries into their global Claude configuration, which is not something
 * to do without an explicit click. A click that cannot be honoured puts the
 * checkbox back where it was and says why, so it can never show "on" while
 * nothing is listening.
 */
function hookMenuItems(): Electron.MenuItemConstructorOptions[] {
  const channel = hooks
  if (channel === null) return []
  return [
    {
      label: HOOKS_MENU_LABEL,
      type: 'checkbox',
      checked: channel.isActive(),
      click: (item) => {
        void (async () => {
          const outcome = await applyHookToggle(channel, item.checked)
          if (outcome.warning !== undefined) {
            console.warn(`[tray] Instant updates: ${outcome.warning}`)
          }
          await refreshTrayMenu()
        })()
      }
    }
  ]
}

async function refreshTrayMenu(): Promise<void> {
  if (!tray) return
  const autostartOn = await isAutostartEnabled()
  const menu = Menu.buildFromTemplate([
    { label: 'Show/Hide Panel', click: () => togglePanel() },
    { type: 'separator' },
    {
      label: autostartMenuLabel(currentPlatform()),
      type: 'checkbox',
      checked: autostartOn,
      click: (item) => {
        void (async () => {
          try {
            if (item.checked) {
              await enableAutostart()
            } else {
              await disableAutostart()
            }
          } catch (error) {
            console.warn('[tray] Failed to update autostart:', error)
          }
          await refreshTrayMenu()
        })()
      }
    },
    ...hookMenuItems(),
    { type: 'separator' },
    { label: 'Quit', click: () => app.quit() }
  ])
  tray.setContextMenu(menu)
}
