import { Menu, Tray, app, nativeImage } from 'electron'
import {
  disable as disableAutostart,
  enable as enableAutostart,
  isEnabled as isAutostartEnabled
} from './autostart'
import { autostartMenuLabel } from './platform/autostartEntries'
import { currentPlatform } from './platform/platform'
import { resolveResourcePath } from './resourcePaths'
import { togglePanel } from './window'

let tray: Tray | null = null

/**
 * Electron's nativeImage automatically picks up a "@2x" sibling for HiDPI
 * displays when the base image is loaded from a file path, so only the
 * 16x16 base name is referenced here — see resources/tray-icon.png and
 * tray-icon@2x.png, both generated by `pnpm icons` from the same painted
 * mound art as the installer and window icons.
 */
function trayIconPath(): string {
  return resolveResourcePath('tray-icon.png', {
    isPackaged: app.isPackaged,
    resourcesPath: process.resourcesPath,
    appPath: app.getAppPath()
  })
}

export async function createTray(): Promise<Tray> {
  const icon = nativeImage.createFromPath(trayIconPath())
  tray = new Tray(icon)
  tray.setToolTip('DwarfAI-Miners')
  tray.on('click', () => togglePanel())
  await refreshTrayMenu()
  return tray
}

async function refreshTrayMenu(): Promise<void> {
  if (!tray) return
  const autostartOn = await isAutostartEnabled()
  const menu = Menu.buildFromTemplate([
    { label: 'Show/Hide Panel', click: () => togglePanel() },
    { type: 'separator' },
    {
      label: autostartMenuLabel(currentPlatform()),
      type: 'checkbox',
      checked: autostartOn,
      click: (item) => {
        void (async () => {
          try {
            if (item.checked) {
              await enableAutostart()
            } else {
              await disableAutostart()
            }
          } catch (error) {
            console.warn('[tray] Failed to update autostart:', error)
          }
          await refreshTrayMenu()
        })()
      }
    },
    { type: 'separator' },
    { label: 'Quit', click: () => app.quit() }
  ])
  tray.setContextMenu(menu)
}
