import { join } from 'node:path'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { fakeSafeStorage } from '../adapters/fakeSafeStorage'
import { createJevApiKeyStore, type JevApiKeyFsLike } from './jevApiKey'

/**
 * The encrypted store behind Settings' Jev API-key control (#509): a
 * user-entered TypeSafe key, entered, replaced and cleared — never shipped or
 * generated by this app.
 *
 * Storage mirrors the pin, edge, audio and notification preferences: one tiny
 * JSON document under userData, rewritten atomically through a sibling temp
 * file plus a rename, with an injected fs so the tests need no real disk. The
 * one thing every OTHER preference store here skips and this one cannot: the
 * document holds ciphertext, never the key, so `safeStorage` is injected too
 * — a hand-written fake (`fakeSafeStorage`), never `vi.mock`.
 */
const USER_DATA_DIR = 'C:/fake/userData'
// Joined the same way the store joins it, rather than assumed as a literal:
// path.join normalizes separators per-platform, and a hardcoded forward-slash
// path would silently miss every lookup on a host that backslashes it.
const FILE = join(USER_DATA_DIR, 'jev-api-key-v1.json')

function fakeFs(initial: Record<string, string> = {}) {
  const files = new Map(Object.entries(initial))
  const events: string[] = []
  const fs: JevApiKeyFsLike = {
    readFile: async (path) => {
      const content = files.get(path)
      if (content === undefined) {
        throw Object.assign(new Error(`ENOENT: ${path}`), { code: 'ENOENT' })
      }
      return content
    },
    writeFile: async (path, data) => {
      files.set(path, data)
      events.push(`write:${path}`)
    },
    rename: async (from, to) => {
      const content = files.get(from)
      if (content === undefined) throw new Error(`ENOENT: ${from}`)
      files.delete(from)
      files.set(to, content)
      events.push(`rename:${from}->${to}`)
    }
  }
  return { fs, files, events }
}

describe('createJevApiKeyStore — a fresh install', () => {
  it('answers unconfigured on a first run, with no file to read', async () => {
    const { fs } = fakeFs()
    const store = createJevApiKeyStore({
      userDataDir: USER_DATA_DIR,
      fs,
      safeStorage: fakeSafeStorage()
    })
    expect(await store.load()).toEqual({ configured: false })
  })

  it('exposes no key through readKey() before anything was ever loaded or saved', () => {
    const store = createJevApiKeyStore({
      userDataDir: USER_DATA_DIR,
      fs: fakeFs().fs,
      safeStorage: fakeSafeStorage()
    })
    expect(store.readKey()).toBeUndefined()
  })
})

describe('createJevApiKeyStore — saving a key', () => {
  it('trims the key, saves it, and reads it back after a "restart" (a fresh store on the same file)', async () => {
    const { fs } = fakeFs()
    const safeStorage = fakeSafeStorage()
    const store = createJevApiKeyStore({ userDataDir: USER_DATA_DIR, fs, safeStorage })

    expect(await store.save('  sk-typesafe-abc123  ')).toEqual({ saved: true })
    expect(store.readKey()).toBe('sk-typesafe-abc123')

    const rebooted = createJevApiKeyStore({ userDataDir: USER_DATA_DIR, fs, safeStorage })
    expect(await rebooted.load()).toEqual({ configured: true })
    expect(rebooted.readKey()).toBe('sk-typesafe-abc123')
  })

  it('persists ONLY the encrypted bytes, never the plaintext key', async () => {
    const { fs, files } = fakeFs()
    const store = createJevApiKeyStore({
      userDataDir: USER_DATA_DIR,
      fs,
      safeStorage: fakeSafeStorage()
    })
    await store.save('sk-typesafe-secret')
    const stored = files.get(FILE) ?? ''
    expect(stored).not.toContain('sk-typesafe-secret')
    expect(JSON.parse(stored)).toEqual({ encrypted: expect.any(String) })
  })

  it('writes atomically: a sibling temp file first, then a rename onto the final path', async () => {
    const { fs, events } = fakeFs()
    const store = createJevApiKeyStore({
      userDataDir: USER_DATA_DIR,
      fs,
      safeStorage: fakeSafeStorage()
    })
    await store.save('sk-typesafe-abc123')
    expect(events).toHaveLength(2)
    const [write = '', rename = ''] = events
    expect(write.startsWith(`write:${FILE}`)).toBe(true)
    expect(write).not.toBe(`write:${FILE}`)
    expect(rename.endsWith(`->${FILE}`)).toBe(true)
  })

  it('refuses an empty key, including one that is only whitespace, without touching the file', async () => {
    const { fs, events } = fakeFs()
    const store = createJevApiKeyStore({
      userDataDir: USER_DATA_DIR,
      fs,
      safeStorage: fakeSafeStorage()
    })
    expect(await store.save('   ')).toEqual({ saved: false, reason: 'empty' })
    expect(events).toHaveLength(0)
    expect(store.readKey()).toBeUndefined()
  })

  it('checks for an empty key before it ever asks whether encryption is available', async () => {
    // The refusal reason must name what is actually wrong: a blank field is
    // never "this machine cannot encrypt", whatever the OS reports.
    const store = createJevApiKeyStore({
      userDataDir: USER_DATA_DIR,
      fs: fakeFs().fs,
      safeStorage: fakeSafeStorage({ available: false })
    })
    expect(await store.save('')).toEqual({ saved: false, reason: 'empty' })
  })

  it('replaces a previously saved key on a second save', async () => {
    const { fs } = fakeFs()
    const safeStorage = fakeSafeStorage()
    const store = createJevApiKeyStore({ userDataDir: USER_DATA_DIR, fs, safeStorage })
    await store.save('sk-old')
    await store.save('sk-new')
    expect(store.readKey()).toBe('sk-new')

    const rebooted = createJevApiKeyStore({ userDataDir: USER_DATA_DIR, fs, safeStorage })
    await rebooted.load()
    expect(rebooted.readKey()).toBe('sk-new')
  })
})

describe('createJevApiKeyStore — no plaintext fallback, ever', () => {
  it('refuses to save when this machine offers no encryption', async () => {
    const { fs, events } = fakeFs()
    const store = createJevApiKeyStore({
      userDataDir: USER_DATA_DIR,
      fs,
      safeStorage: fakeSafeStorage({ available: false })
    })
    expect(await store.save('sk-typesafe-abc123')).toEqual({
      saved: false,
      reason: 'encryption-unavailable'
    })
    expect(events).toHaveLength(0)
    expect(store.readKey()).toBeUndefined()
  })

  it('reports load() as unavailable, with the reason, rather than as merely unconfigured', async () => {
    const store = createJevApiKeyStore({
      userDataDir: USER_DATA_DIR,
      fs: fakeFs().fs,
      safeStorage: fakeSafeStorage({ available: false })
    })
    expect(await store.load()).toEqual({
      configured: false,
      unavailableReason: 'encryption-unavailable'
    })
  })

  it('reports unavailable even when a key was stored on a machine that could once encrypt', async () => {
    // The keyring can go away under a stored file — a locked wallet, a moved
    // profile — and the honest answer is WHY nothing can be read, not that
    // nothing was ever set.
    const { fs } = fakeFs()
    const available = createJevApiKeyStore({
      userDataDir: USER_DATA_DIR,
      fs,
      safeStorage: fakeSafeStorage()
    })
    await available.save('sk-typesafe-abc123')

    const nowUnavailable = createJevApiKeyStore({
      userDataDir: USER_DATA_DIR,
      fs,
      safeStorage: fakeSafeStorage({ available: false })
    })
    expect(await nowUnavailable.load()).toEqual({
      configured: false,
      unavailableReason: 'encryption-unavailable'
    })
    expect(nowUnavailable.readKey()).toBeUndefined()
  })
})

describe('createJevApiKeyStore — a corrupt or undecryptable file', () => {
  let warn: ReturnType<typeof vi.spyOn>

  beforeEach(() => {
    warn = vi.spyOn(console, 'warn').mockImplementation(() => undefined)
  })

  afterEach(() => {
    warn.mockRestore()
  })

  it('treats unparseable JSON as "not configured", never blocking startup', async () => {
    const store = createJevApiKeyStore({
      userDataDir: USER_DATA_DIR,
      fs: fakeFs({ [FILE]: '{ not json' }).fs,
      safeStorage: fakeSafeStorage()
    })
    await expect(store.load()).resolves.toEqual({ configured: false })
  })

  it('treats a document missing the encrypted field the same way', async () => {
    const store = createJevApiKeyStore({
      userDataDir: USER_DATA_DIR,
      fs: fakeFs({ [FILE]: '{}' }).fs,
      safeStorage: fakeSafeStorage()
    })
    await expect(store.load()).resolves.toEqual({ configured: false })
  })

  it('treats ciphertext that will not decrypt as corruption, and warns by name', async () => {
    // Bytes that are not this fake's own encrypted shape at all — the
    // equivalent of a file safeStorage's real decryptString would refuse.
    const garbage = Buffer.from('not-really-encrypted').toString('base64')
    const store = createJevApiKeyStore({
      userDataDir: USER_DATA_DIR,
      fs: fakeFs({ [FILE]: JSON.stringify({ encrypted: garbage }) }).fs,
      safeStorage: fakeSafeStorage()
    })
    await expect(store.load()).resolves.toEqual({ configured: false })
    expect(store.readKey()).toBeUndefined()
    expect(warn).toHaveBeenCalledWith(expect.stringContaining('[jev]'), expect.anything())
  })

  it('never throws on a corrupt file, the same "never worth failing startup over" rule every preference here holds', async () => {
    const store = createJevApiKeyStore({
      userDataDir: USER_DATA_DIR,
      fs: fakeFs({ [FILE]: '[]' }).fs,
      safeStorage: fakeSafeStorage()
    })
    await expect(store.load()).resolves.not.toThrow()
  })
})

describe('createJevApiKeyStore — clearing a key', () => {
  it('forgets the key: readKey() clears immediately, and it stays cleared after a "restart"', async () => {
    const { fs } = fakeFs()
    const safeStorage = fakeSafeStorage()
    const store = createJevApiKeyStore({ userDataDir: USER_DATA_DIR, fs, safeStorage })
    await store.save('sk-typesafe-abc123')

    await store.clear()
    expect(store.readKey()).toBeUndefined()

    const rebooted = createJevApiKeyStore({ userDataDir: USER_DATA_DIR, fs, safeStorage })
    expect(await rebooted.load()).toEqual({ configured: false })
  })

  it('clearing when nothing was ever saved is a no-op, not a refusal', async () => {
    const store = createJevApiKeyStore({
      userDataDir: USER_DATA_DIR,
      fs: fakeFs().fs,
      safeStorage: fakeSafeStorage()
    })
    await expect(store.clear()).resolves.toBeUndefined()
    expect(store.readKey()).toBeUndefined()
  })
})
