// Wire name → 14 id (14 §2.1 `A-01` … `A-X1`), used by the router (EPIC-04) and the registry tests. Every CHANNELS
// key is here; A-44 is also listed under its today wire `panel:openMine`, A-X1 under its member name (it has no
// wire), and the two legacy rows of 14 §8 I-21 (AMENDMENT-12) carry that reference instead of an id.
export type RowId = `A-${string}` | '§8 I-21'

export const ROW_IDS: Readonly<Record<string, RowId>> = {
  'panel:hide': 'A-01',
  'panel:raise': 'A-02',
  'panel:getAlwaysOnTop': 'A-03',
  'panel:setAlwaysOnTop': 'A-04',
  'panel:visible:get': 'A-05',
  'audio:preferences:get': 'A-06',
  'audio:preferences:set': 'A-07',
  'panel:layout:get': 'A-08',
  'panel:layout:set': 'A-09',
  'shortcut:get': 'A-10',
  'shortcut:set': 'A-11',
  'mines:get': 'A-12',
  'dwarf:activate': 'A-13',
  'dwarf:feed': 'A-14',
  'dwarf:feed:page': 'A-15',
  'panel:watchDwarfFeed': 'A-16',
  'dwarf:refreshTelemetry': 'A-17',
  'dwarf:setTuning': 'A-18',
  'mine:history': 'A-19',
  'mine:openPath': 'A-20',
  'shell:openExternalLink': 'A-21',
  'shell:copyText': 'A-22',
  'dwarf:sendText': 'A-23',
  'dwarf:attachments:choose': 'A-24',
  'dwarf:attachments:describe': 'A-25',
  'dwarf:kick': 'A-26',
  'dwarf:retire': 'A-27',
  'app:build': 'A-28',
  'app:features': 'A-29',
  'mine:declare': 'A-30',
  'mine:declare-main': 'A-31',
  'mine:undeclare': 'A-32',
  'metrics:reset': 'A-33',
  'projects:query': 'A-34',
  'agent:launch': 'A-35',
  'agent:providers': 'A-36',
  'agent:models': 'A-37',
  'agent:launchHeld': 'A-38',
  'agent:launchHosted': 'A-39',
  'agent:answerQuestion': 'A-40',
  'agent:answerPermission': 'A-41',
  'notifications:enabled:get': 'A-42',
  'notifications:enabled:set': 'A-43',
  'presence:visibleMines': 'A-44',
  'panel:openMine': 'A-44',
  'typography:preferences:get': 'A-45',
  'typography:preferences:set': 'A-46',
  'jev:settings:get': 'A-47',
  'jev:apiKey:set': 'A-48',
  'jev:apiKey:clear': 'A-49',
  'jev:route': 'A-50',
  'jev:preferences:set': 'A-51',
  'opencode:settings:get': 'A-52',
  'opencode:plugin:set': 'A-53',
  'opencode:password:set': 'A-54',
  'opencode:password:clear': 'A-55',
  'launch-view:get': 'A-56',
  'launch-view:set': 'A-57',
  'panel:visible:changed': 'A-P1',
  'mines:update': 'A-P2',
  'agent:launchFailed': 'A-P3',
  'dwarf:sendText:settled': 'A-P4',
  'panel:mine:show': 'A-P5',
  'typography:preferences:changed': 'A-P6',
  pathForDroppedFile: 'A-X1',
  'dwarf:setName': '§8 I-21',
  'dwarf:resetName': '§8 I-21',
  // NEW rows of 14 §2.2, each declared by the issue that builds its handler (22 §5)
  'diag:renderer:report': 'A-N30',
  'tray:stopEverything:requested': 'A-N25',
  'tray:stopEverything:confirm': 'A-N26',
  'tray:stopEverything:cancel': 'A-N27',
  'tray:stopEverything:request': 'A-N34',
  'host:connection:get': 'A-N03',
  'host:connection:changed': 'A-N04',
  'host:connection:retry': 'A-N05',
  'host:connection:confirm-restart': 'A-N33',
  'ui:session:get': 'A-N17',
  'ui:session:patch': 'A-N18',
  'ui:session:changed': 'A-N19',
  'ui:preferences:get': 'A-N20',
  'ui:preferences:set': 'A-N21',
  'ui:preferences:reset': 'A-N12',
  'host:snapshot': 'A-N01',
  'host:event': 'A-N02',
  'mode:revealDwarfChat': 'A-N16',
  'claude:hooks:set': 'A-N31',
  'ask:step:set': 'A-N07',
  'welcome:answer': 'A-N32'
}
