// The representative rows of each DB fixture ladder rung (17 §1.5; 21 §5.1; ADR-005 item 6),
// dumped by `scripts/db/dump-fixture.mjs --seed <release>` into `fixtures/db/<release>.sql` and
// regenerated by the ladder test to prove the committed rung has not drifted. Never imported by
// production code (R14).
//
// Append only, like the migrations: a seed is written against its release's schema and is never
// edited once its rung is committed (an edit is a reviewed regeneration of that rung). A release
// that changes the schema adds its own seed and rung (see `fixtures/db/README.md`). Values are
// synthetic and neutral: no real path, account, host or address (17 §1.4).
import type { FixtureSeed } from './fixtureDump'

const T = 1_750_000_000_000
const MINE = '00000000-0000-7000-8000-00000000c0f1'
const DWARF = '00000000-0000-7000-8000-00000000c0d1'
const PERSON_MESSAGE = '00000000-0000-7000-8000-00000000c0a1'
const DWARF_MESSAGE = '00000000-0000-7000-8000-00000000c0a2'
const DWARF_REPLY = '00000000-0000-7000-8000-00000000c0a3'
const STREAM = 'claude:session-c0-1'
const UNIT = 'claude:session-c0-1:msg-2'

/**
 * Cut 0 (schema v1): the 09 §4.9 seed rows of migration 1 plus one measured mine, one foreman
 * dwarf observed from its transcript, three messages (one sent from DwarfAI with its delivery,
 * two from the transcript with their keys, one of them over two lines), and one sealed usage unit
 * credited as one bronze ledger entry, whose totals row the ledger trigger writes.
 */
const cut0: FixtureSeed = {
  release: 'cut-0',
  version: 1,
  statements: [
    `INSERT INTO mines (id, canonical_path, name, name_norm, state, tier, source_weight_bytes,
       has_been_measured, measured_at, created_at, last_used_at)
     VALUES ('${MINE}', '/work/mine-one', 'mine-one', 'mine-one', 'active', 'bronze', 524288,
       1, ${T + 1_000}, ${T}, ${T + 60_000})`,
    `INSERT INTO dwarfs (id, mine_id, provider_id, provider_session_id, base_name, rank,
       process_state, turn_state, turn_ended_at, turn_end_reliability, arrived_at,
       last_activity_at, workplace_path)
     VALUES ('${DWARF}', '${MINE}', 'claude', 'session-c0-1', 'Durin', 'foreman', 'running',
       'ended', ${T + 50_000}, 'reliable', ${T + 2_000}, ${T + 50_000}, '/work/mine-one')`,
    `INSERT INTO dwarf_lifecycle_facts (id, dwarf_id, type, occurred_at, recorded_at)
     VALUES ('00000000-0000-7000-8000-00000000c0e1', '${DWARF}', 'DwarfArrived', ${T + 2_000},
       ${T + 2_000})`,
    `INSERT INTO source_cursors (stream_id, adapter_id, kind, value, updated_at)
     VALUES ('${STREAM}', 'claude-transcript', 'byte-offset', 2048, ${T + 50_000})`,
    `INSERT INTO observed_sessions (dwarf_id, cwd, first_seen_at, last_record_at)
     VALUES ('${DWARF}', '/work/mine-one', ${T + 2_000}, ${T + 50_000})`,
    `INSERT INTO observed_session_streams (dwarf_id, stream_id) VALUES ('${DWARF}', '${STREAM}')`,
    `INSERT INTO messages (id, dwarf_id, role, text, origin, created_at, request_id)
     VALUES ('${PERSON_MESSAGE}', '${DWARF}', 'person', 'Please add the README section.',
       'dwarfai', ${T + 10_000}, 'req-c0-1')`,
    `INSERT INTO deliveries (message_id, dwarf_id, kind, phase, confidence, sent_at, phase_at)
     VALUES ('${PERSON_MESSAGE}', '${DWARF}', 'message', 'delivered', 'confirmed', ${T + 10_000},
       ${T + 10_500})`,
    `INSERT INTO messages (id, dwarf_id, source_key, role, text, origin, provider_time, created_at)
     VALUES ('${DWARF_MESSAGE}', '${DWARF}', '${UNIT}', 'dwarf', 'On it.', 'transcript',
       ${T + 11_000}, ${T + 11_200})`,
    `INSERT INTO messages (id, dwarf_id, source_key, role, text, origin, provider_time, created_at)
     VALUES ('${DWARF_REPLY}', '${DWARF}', 'claude:session-c0-1:msg-3', 'dwarf',
       'Added the section.' || char(10) || 'It''s under "Usage".', 'transcript', ${T + 49_000},
       ${T + 49_300})`,
    `INSERT INTO message_keys (source_key, dwarf_id, message_id, first_seen_at)
     VALUES ('${UNIT}', '${DWARF}', '${DWARF_MESSAGE}', ${T + 11_200})`,
    `INSERT INTO message_keys (source_key, dwarf_id, message_id, first_seen_at)
     VALUES ('claude:session-c0-1:msg-3', '${DWARF}', '${DWARF_REPLY}', ${T + 49_300})`,
    `INSERT INTO usage_units (unit_key, dwarf_id, mine_id, sealed, provider_time,
       first_observed_at, sealed_at)
     VALUES ('${UNIT}', '${DWARF}', '${MINE}', 1, ${T + 11_000}, ${T + 11_200}, ${T + 12_000})`,
    `INSERT INTO usage_observations (source_key, unit_key, path, fidelity, input_net, output,
       cache_read, sealed, provider_time, observed_at)
     VALUES ('${UNIT}:usage', '${UNIT}', 'transcript', 2, 1000, 200, 4000, 1, ${T + 11_000},
       ${T + 11_200})`,
    `INSERT INTO ledger_entries (id, unit_key, mine_id, material, tokens, units, kind, source_key,
       credited_at)
     VALUES ('00000000-0000-7000-8000-00000000c0b1', '${UNIT}', '${MINE}', 'bronze', 1200, 1,
       'live', '${UNIT}:usage', ${T + 12_000})`
  ]
}

/** Every release's seed, by release name. */
export const fixtureSeeds: Readonly<Record<string, FixtureSeed>> = {
  'cut-0': cut0
}
