// The normalised text of `schema.snapshot.sql` (17 §1.5 "From empty"; 09 §6.5 "Schema snapshot"),
// shared by `schema.contract.test.ts` and `scripts/db/dump-schema.mjs`, so the test and the
// generator can never normalise differently.
//
// Every schema object that has SQL text (SQLite's automatic indexes have none, and `sqlite_*`
// objects are SQLite's own), sorted by type, then name; its text with line ends as LF, trailing
// whitespace removed and a closing `;`; objects separated by one blank line.
import type { SqliteRow } from '../../../kernel/ports/sqliteDatabase'

/** The `sqlite_schema` rows a snapshot is rendered from. */
export const SCHEMA_QUERY = 'SELECT type, name, sql FROM sqlite_schema'

export const SNAPSHOT_HEADER = [
  '-- sqlite_schema of an empty file migrated to head (09 §4, 17 §1.5). Generated by',
  '-- scripts/db/dump-schema.mjs; never edited by hand: a schema change is a new migration.'
].join('\n')

function compareText(a: string, b: string): number {
  return a < b ? -1 : a > b ? 1 : 0
}

function canonicalSql(sql: string): string {
  return sql
    .replace(/\r\n?/g, '\n')
    .split('\n')
    .map((line) => line.trimEnd())
    .join('\n')
    .trim()
}

/** Render the rows of `SCHEMA_QUERY` as the snapshot text. */
export function renderSchemaSnapshot(rows: readonly SqliteRow[]): string {
  const entries = rows
    .filter((row) => typeof row['sql'] === 'string' && !String(row['name']).startsWith('sqlite_'))
    .map((row) => ({
      type: String(row['type']),
      name: String(row['name']),
      sql: String(row['sql'])
    }))
    .sort((a, b) => compareText(a.type, b.type) || compareText(a.name, b.name))
    .map((entry) => `${canonicalSql(entry.sql)};`)
  return `${[SNAPSHOT_HEADER, ...entries].join('\n\n')}\n`
}
