/**
 * The mine interior's logical map: every place a dwarf can stand, and every
 * corridor between them, in percent of the painting.
 *
 * GENERATED by `node scripts/build-interior-map.mjs` from
 * `docs/mine-interior-features.json` — never edit the coordinates by hand.
 * That script's header carries the whole argument: why the extracted dataset's
 * own percentages are NOT these ones, how the panel's art box was measured, and
 * why one topology serves all five tiers. Read it before changing a number.
 *
 * ## The coordinate space
 *
 * Percentages of the PAINTING (`inside-mines/inside-<tier>-mine.jpg`,
 * 1184x3622), not of the rendered box — the convention
 * `.claude/rules/coordinates.md` calls image percent, projected to the box at
 * render time by `sceneGeometry.projectToBox`. All five tier paintings share
 * one composition and therefore one map; only the ore is recoloured.
 *
 * ## Order is load-bearing
 *
 * Stations keep the extraction's own order within each class, because a
 * station's INDEX inside its class is the slot `sceneAssignment` hashes a
 * dwarf id onto. Re-ordering this list moves every dwarf in every mine.
 */

/** A point on the painting, in percent of the painting's own canvas. */
export interface InteriorPoint {
  x: number
  y: number
}

/**
 * What the design's spatial map draws at a point (`screens/mine.md`): a red
 * spawn circle, a blue worker triangle, an orange foreman diamond, a purple
 * ladder arrow or a magenta ramp square.
 */
export type InteriorStationKind = 'spawn' | 'worker' | 'foreman' | 'ladder' | 'ramp'

/** One extracted marker, at the dwarf's feet. */
export interface InteriorStation extends InteriorPoint {
  id: string
  kind: InteriorStationKind
}

/** A junction or endpoint of the passable-path network. */
export interface RouteNode extends InteriorPoint {
  id: number
}

/**
 * One corridor between two junctions, as the ordered points the gray route line
 * actually passes through — a polyline, not a straight line, so a dwarf walking
 * it follows the painted stair rather than cutting through the rock.
 */
export interface RouteEdge {
  from: number
  to: number
  points: readonly InteriorPoint[]
  /**
   * True for the one edge that was not extracted: the seam joining the
   * entrance stub to the main network, which the route mask reports as a
   * separate component only because the painted entrance decoration covers the
   * pixels that connect them (docs/map-coordinates.md §3.2).
   */
  bridged?: boolean
}

/**
 * The panel box `docs/mine-interior-features.json` measured its own
 * percentages against, and where inside it that panel draws the painting.
 *
 * Carried here so the bridge is checkable from the data rather than only from
 * the generator: `interiorMap.test.ts` re-derives every coordinate below from
 * the committed dataset through these two boxes, so a hand-edited number and a
 * stale regeneration both fail loudly.
 */
export const PANEL_BOX = { width: 182, height: 579 } as const

/**
 * The pixel size of the painting these percentages are percentages OF — the
 * five `inside-mines/inside-<tier>-mine.jpg` files, which share it (Cropper is
 * 2px shorter, 0.06%, and shares the map like the rest).
 *
 * A deliberate copy of `art.ts`'s `INTERIOR_ART_SIZE`, kept here because a
 * coordinate space belongs with the coordinates: this module is authored
 * against the painting, and reading its own ratio out of the art barrel would
 * make the map depend on the bundler. `interiorMap.test.ts` holds the two
 * equal, so the copy cannot drift unnoticed.
 */
export const INTERIOR_PAINTING_SIZE = { width: 1184, height: 3622 } as const

export const PANEL_ART_BOX = {
  x: 0.6,
  y: 29.34,
  width: 179.1,
  height: 548.57
} as const

/** Every marker the design's work-point sheet draws, re-anchored to the painting. */
export const INTERIOR_STATIONS: readonly InteriorStation[] = [
  { id: 'spawn-1', kind: 'spawn', x: 44.54, y: 22.5 },
  { id: 'spawn-2', kind: 'spawn', x: 9.73, y: 37.13 },
  { id: 'spawn-3', kind: 'spawn', x: 38.97, y: 90.44 },
  { id: 'worker-1', kind: 'worker', x: 43.77, y: 10.02 },
  { id: 'worker-2', kind: 'worker', x: 59.42, y: 11.07 },
  { id: 'worker-3', kind: 'worker', x: 14.05, y: 14.89 },
  { id: 'worker-4', kind: 'worker', x: 84.92, y: 15.62 },
  { id: 'worker-5', kind: 'worker', x: 61.83, y: 24.94 },
  { id: 'worker-6', kind: 'worker', x: 30.99, y: 34.81 },
  { id: 'worker-7', kind: 'worker', x: 14.08, y: 42.44 },
  { id: 'worker-8', kind: 'worker', x: 82.88, y: 51.95 },
  { id: 'worker-9', kind: 'worker', x: 28.94, y: 53.17 },
  { id: 'worker-10', kind: 'worker', x: 16.15, y: 55.59 },
  { id: 'worker-11', kind: 'worker', x: 66.18, y: 65.75 },
  { id: 'worker-12', kind: 'worker', x: 48.48, y: 68.69 },
  { id: 'worker-13', kind: 'worker', x: 82.9, y: 69.77 },
  { id: 'worker-14', kind: 'worker', x: 14.08, y: 70.5 },
  { id: 'worker-15', kind: 'worker', x: 22.52, y: 83.62 },
  { id: 'worker-16', kind: 'worker', x: 74.58, y: 84.35 },
  { id: 'worker-17', kind: 'worker', x: 50.96, y: 91.09 },
  { id: 'worker-18', kind: 'worker', x: 68.24, y: 92.07 },
  { id: 'foreman-1', kind: 'foreman', x: 56.87, y: 47.7 },
  { id: 'foreman-2', kind: 'foreman', x: 68.21, y: 49.02 },
  { id: 'foreman-3', kind: 'foreman', x: 61.92, y: 52.53 },
  { id: 'ladder-1', kind: 'ladder', x: 80.93, y: 25.28 },
  { id: 'ladder-2', kind: 'ladder', x: 21.74, y: 26.49 },
  { id: 'ladder-3', kind: 'ladder', x: 80.97, y: 40.89 },
  { id: 'ladder-4', kind: 'ladder', x: 80.9, y: 63.28 },
  { id: 'ladder-5', kind: 'ladder', x: 82.02, y: 79.16 },
  { id: 'ramp-1', kind: 'ramp', x: 48.52, y: 33.49 },
  { id: 'ramp-2', kind: 'ramp', x: 41.8, y: 47.74 },
  { id: 'ramp-3', kind: 'ramp', x: 35.7, y: 62.33 },
  { id: 'ramp-4', kind: 'ramp', x: 31.23, y: 78.17 }
]

/** The junctions and endpoints of the passable-path network. */
export const INTERIOR_ROUTE_NODES: readonly RouteNode[] = [
  { id: 0, x: 45.45, y: 22.91 },
  { id: 1, x: 66.25, y: 26.19 },
  { id: 2, x: 80.49, y: 28.92 },
  { id: 3, x: 22.14, y: 38.95 },
  { id: 4, x: 7.48, y: 38.95 },
  { id: 5, x: 23.6, y: 40.54 },
  { id: 6, x: 79.09, y: 50.39 },
  { id: 7, x: 66.11, y: 52.94 },
  { id: 8, x: 79.88, y: 53.59 },
  { id: 9, x: 15.86, y: 54.44 },
  { id: 10, x: 80.76, y: 55.17 },
  { id: 11, x: 91.23, y: 55.35 },
  { id: 12, x: 23.89, y: 67.91 },
  { id: 13, x: 63.65, y: 68.3 },
  { id: 14, x: 86.77, y: 70.49 },
  { id: 15, x: 81.63, y: 70.81 },
  { id: 16, x: 23.12, y: 82.52 },
  { id: 17, x: 75.6, y: 84.16 },
  { id: 18, x: 64.43, y: 93.27 },
  { id: 19, x: 44.33, y: 95.82 }
]

/** The corridors between them, each carrying the shape of its own stretch. */
export const INTERIOR_ROUTE_EDGES: readonly RouteEdge[] = [
  {
    from: 1,
    to: 2,
    points: [
      { x: 66.67, y: 26.19 },
      { x: 71.13, y: 26.19 },
      { x: 72.81, y: 26.73 },
      { x: 74.48, y: 28.74 },
      { x: 80.07, y: 28.92 }
    ]
  },
  {
    from: 2,
    to: 6,
    points: [
      { x: 80.63, y: 29.1 },
      { x: 80.07, y: 50.07 }
    ]
  },
  {
    from: 4,
    to: 5,
    points: [
      { x: 7.48, y: 38.95 },
      { x: 14.18, y: 38.95 },
      { x: 17.53, y: 40.59 },
      { x: 22.56, y: 40.41 }
    ]
  },
  {
    from: 3,
    to: 5,
    points: [
      { x: 22, y: 39.13 },
      { x: 22.56, y: 40.22 }
    ]
  },
  {
    from: 6,
    to: 8,
    points: [
      { x: 80.07, y: 50.25 },
      { x: 80.07, y: 53.53 }
    ]
  },
  {
    from: 7,
    to: 8,
    points: [
      { x: 66.67, y: 52.99 },
      { x: 77.28, y: 52.99 },
      { x: 79.51, y: 53.53 }
    ]
  },
  {
    from: 8,
    to: 10,
    points: [
      { x: 80.07, y: 53.71 },
      { x: 80.63, y: 54.99 }
    ]
  },
  {
    from: 10,
    to: 11,
    points: [
      { x: 81.18, y: 55.17 },
      { x: 91.23, y: 55.35 }
    ]
  },
  {
    from: 10,
    to: 13,
    points: [
      { x: 80.63, y: 55.35 },
      { x: 80.63, y: 65.56 },
      { x: 79.51, y: 65.93 },
      { x: 67.23, y: 66.11 },
      { x: 64.43, y: 66.84 },
      { x: 63.87, y: 68.12 }
    ]
  },
  {
    from: 14,
    to: 15,
    points: [
      { x: 86.77, y: 70.49 },
      { x: 82.3, y: 70.67 }
    ]
  },
  {
    from: 15,
    to: 17,
    points: [
      { x: 81.18, y: 71.03 },
      { x: 80.63, y: 83.61 },
      { x: 78.95, y: 84.16 },
      { x: 75.6, y: 84.16 }
    ]
  },
  {
    from: 12,
    to: 16,
    points: [
      { x: 22.56, y: 68.3 },
      { x: 17.53, y: 68.48 },
      { x: 15.3, y: 69.21 },
      { x: 14.74, y: 70.49 },
      { x: 15.3, y: 70.85 },
      { x: 21.44, y: 71.03 },
      { x: 24.23, y: 72.13 },
      { x: 24.79, y: 73.77 },
      { x: 30.37, y: 74.5 },
      { x: 31.49, y: 75.04 },
      { x: 31.49, y: 81.6 },
      { x: 28.7, y: 82.52 },
      { x: 23.12, y: 82.52 }
    ]
  },
  {
    from: 12,
    to: 13,
    points: [
      { x: 25.35, y: 67.57 },
      { x: 28.7, y: 68.84 },
      { x: 33.72, y: 69.57 },
      { x: 59.41, y: 69.57 },
      { x: 62.76, y: 68.48 }
    ]
  },
  {
    from: 13,
    to: 15,
    points: [
      { x: 64.43, y: 68.3 },
      { x: 72.25, y: 68.3 },
      { x: 74.48, y: 69.03 },
      { x: 75.6, y: 70.3 },
      { x: 81.74, y: 70.67 }
    ]
  },
  {
    from: 7,
    to: 12,
    points: [
      { x: 65.55, y: 52.99 },
      { x: 61.08, y: 53.71 },
      { x: 58.85, y: 55.35 },
      { x: 51.03, y: 55.72 },
      { x: 48.24, y: 57.91 },
      { x: 43.22, y: 58.45 },
      { x: 40.98, y: 59.37 },
      { x: 40.98, y: 60.28 },
      { x: 35.96, y: 61.37 },
      { x: 34.84, y: 62.83 },
      { x: 28.14, y: 63.38 },
      { x: 25.91, y: 64.1 },
      { x: 24.79, y: 67.39 }
    ]
  },
  {
    from: 5,
    to: 9,
    points: [
      { x: 24.79, y: 40.77 },
      { x: 28.14, y: 40.95 },
      { x: 31.49, y: 41.87 },
      { x: 32.05, y: 44.6 },
      { x: 39.87, y: 45.88 },
      { x: 41.54, y: 47.88 },
      { x: 43.77, y: 48.61 },
      { x: 50.47, y: 48.79 },
      { x: 54.38, y: 49.89 },
      { x: 55.5, y: 52.07 },
      { x: 54.38, y: 52.99 },
      { x: 48.24, y: 54.44 },
      { x: 15.86, y: 54.44 }
    ]
  },
  {
    from: 6,
    to: 7,
    points: [
      { x: 77.83, y: 50.62 },
      { x: 75.04, y: 51.16 },
      { x: 68.34, y: 51.16 },
      { x: 66.11, y: 51.89 },
      { x: 66.11, y: 52.8 }
    ]
  },
  {
    from: 1,
    to: 3,
    points: [
      { x: 66.11, y: 26.37 },
      { x: 64.43, y: 27.28 },
      { x: 58.29, y: 28.19 },
      { x: 57.73, y: 30.2 },
      { x: 55.5, y: 31.29 },
      { x: 48.8, y: 31.84 },
      { x: 44.89, y: 32.93 },
      { x: 44.33, y: 36.03 },
      { x: 42.66, y: 37.31 },
      { x: 39.31, y: 38.4 },
      { x: 34.84, y: 38.95 },
      { x: 22.56, y: 38.95 }
    ]
  },
  {
    from: 0,
    to: 1,
    points: [
      { x: 45.45, y: 22.91 },
      { x: 56.62, y: 22.91 },
      { x: 58.29, y: 24 },
      { x: 63.32, y: 24.18 },
      { x: 65.55, y: 24.91 },
      { x: 66.11, y: 26.01 }
    ]
  },
  {
    from: 2,
    to: 3,
    points: [
      { x: 80.63, y: 28.74 },
      { x: 80.63, y: 15.25 },
      { x: 76.16, y: 12.88 },
      { x: 72.81, y: 12.15 },
      { x: 66.67, y: 11.79 },
      { x: 35.96, y: 11.79 },
      { x: 29.26, y: 12.33 },
      { x: 24.23, y: 13.79 },
      { x: 22, y: 15.8 },
      { x: 22, y: 38.77 }
    ]
  },
  {
    from: 19,
    to: 18,
    points: [
      { x: 44.33, y: 95.82 },
      { x: 43.77, y: 94.55 },
      { x: 38.75, y: 93.64 },
      { x: 38.19, y: 92.18 },
      { x: 49.36, y: 92.18 },
      { x: 52.71, y: 93.27 },
      { x: 64.43, y: 93.27 }
    ]
  },
  {
    from: 17,
    to: 18,
    points: [
      { x: 75.6, y: 84.16 },
      { x: 64.43, y: 93.27 }
    ],
    bridged: true
  }
]
