-- DwarfAI Host database: fixture ladder rung "cut-0" (ADR-005 item 6; 17 §1.5).
-- Generated by scripts/db/dump-fixture.mjs --seed cut-0; never edited by hand: a
-- regeneration is a reviewed diff. Scrubbed per 17 §1.4 (no home path, user or host name,
-- e-mail address or secret).
-- schema-version: 1
PRAGMA foreign_keys = OFF;
BEGIN;
CREATE TABLE schema_migrations (
  version       INTEGER NOT NULL PRIMARY KEY CHECK (version >= 1),
  name          TEXT    NOT NULL UNIQUE,
  checksum      TEXT    NOT NULL CHECK (length(checksum) = 64),
  applied_at    INTEGER NOT NULL,
  app_version   TEXT    NOT NULL
) STRICT;
CREATE TABLE app_meta (
  id                    INTEGER NOT NULL PRIMARY KEY CHECK (id = 1),
  install_id            TEXT    NOT NULL CHECK (length(install_id) = 36),
  reset_epoch           INTEGER NOT NULL DEFAULT 0 CHECK (reset_epoch >= 0),
  current_host_epoch    TEXT,
  host_epoch_started_at INTEGER,
  host_boot_id          TEXT,
  host_boot_time_ms     INTEGER CHECK (host_boot_time_ms >= 0),
  host_logon_session_id TEXT,
  clean_shutdown_epoch  TEXT,
  clean_shutdown_at     INTEGER,
  clean_shutdown_reason TEXT    CHECK (clean_shutdown_reason IN ('stop-all', 'upgrade', 'os-session-end')),  -- 'idle' retired (AMENDMENT-5, OQ-63)
  ingress_port          INTEGER CHECK (ingress_port BETWEEN 1024 AND 65535),
  welcome_answered_at   INTEGER CHECK (welcome_answered_at >= 0),                                    -- AMENDMENT-7 (OQ-68): NULL = the first-run step is due
  created_at            INTEGER NOT NULL,
  CHECK ((clean_shutdown_epoch IS NULL) = (clean_shutdown_at IS NULL)),
  CHECK ((clean_shutdown_epoch IS NULL) = (clean_shutdown_reason IS NULL)),
  CHECK ((current_host_epoch IS NULL) = (host_epoch_started_at IS NULL)),
  CHECK (current_host_epoch IS NOT NULL
         OR (host_boot_id IS NULL AND host_boot_time_ms IS NULL AND host_logon_session_id IS NULL))
) STRICT;
CREATE TABLE install_moment (
  id                INTEGER NOT NULL PRIMARY KEY CHECK (id = 1),
  at                INTEGER NOT NULL,
  reason            TEXT    NOT NULL CHECK (reason IN ('fresh-install', 'reset')),
  backfill_state    TEXT    NOT NULL DEFAULT 'not-started' CHECK (backfill_state IN ('not-started', 'running', 'paused', 'done')),
  backfill_done_at  INTEGER,
  CHECK ((backfill_state = 'done') = (backfill_done_at IS NOT NULL))
) STRICT;
CREATE TABLE coal_backfill_units (
  scan_unit          TEXT    NOT NULL PRIMARY KEY,
  install_moment_id  INTEGER NOT NULL DEFAULT 1 REFERENCES install_moment (id) ON DELETE CASCADE,
  adapter_id         TEXT    NOT NULL,
  tokens_credited    INTEGER NOT NULL DEFAULT 0 CHECK (tokens_credited >= 0),
  credited_at        INTEGER NOT NULL
) STRICT, WITHOUT ROWID;
CREATE TABLE reset_journal (
  id            TEXT    NOT NULL PRIMARY KEY CHECK (length(id) = 36),
  epoch         INTEGER NOT NULL UNIQUE CHECK (epoch >= 1),
  step          TEXT    NOT NULL CHECK (step IN ('begun', 'db', 'secrets', 'external-config', 'ui-prefs', 'install-moment', 'done')),
  started_at    INTEGER NOT NULL,
  step_at       INTEGER NOT NULL,
  finished_at   INTEGER,
  last_failure  TEXT,
  CHECK ((step = 'done') = (finished_at IS NOT NULL))
) STRICT;
CREATE TABLE mines (
  id                   TEXT    NOT NULL PRIMARY KEY CHECK (length(id) = 36),
  canonical_path       TEXT    NOT NULL UNIQUE CHECK (canonical_path <> ''),
  name                 TEXT    NOT NULL CHECK (name <> ''),
  name_norm            TEXT    NOT NULL,
  state                TEXT    NOT NULL CHECK (state IN ('unrecorded', 'measuring', 'active', 'removed', 'unenterable')),
  tier                 TEXT    CHECK (tier IN ('bronze', 'copper', 'silver', 'gold', 'uranium')),
  source_weight_bytes  INTEGER CHECK (source_weight_bytes >= 0),
  has_been_measured    INTEGER NOT NULL DEFAULT 0 CHECK (has_been_measured IN (0, 1)),
  measured_at          INTEGER,
  unenterable_reason   TEXT,
  removed_at           INTEGER,
  created_at           INTEGER NOT NULL,
  last_used_at         INTEGER NOT NULL,
  map_site_x_pct       REAL    CHECK (map_site_x_pct BETWEEN 0 AND 100),
  map_site_y_pct       REAL    CHECK (map_site_y_pct BETWEEN 0 AND 100),
  CHECK ((state = 'removed') = (removed_at IS NOT NULL)),
  CHECK ((state = 'unenterable') = (unenterable_reason IS NOT NULL)),
  CHECK (tier IS NULL OR has_been_measured = 1),
  CHECK ((has_been_measured = 1) = (measured_at IS NOT NULL)),
  CHECK ((map_site_x_pct IS NULL) = (map_site_y_pct IS NULL))
) STRICT;
CREATE TABLE dwarfs (
  id                            TEXT    NOT NULL PRIMARY KEY CHECK (length(id) = 36),
  mine_id                       TEXT    NOT NULL REFERENCES mines (id) ON DELETE CASCADE,
  provider_id                   TEXT    NOT NULL CHECK (provider_id <> ''),
  provider_session_id           TEXT    NOT NULL CHECK (provider_session_id <> ''),
  provider_agent_id             TEXT    NOT NULL DEFAULT '',
  previous_provider_session_id  TEXT,
  base_name                     TEXT    NOT NULL CHECK (base_name <> ''),
  custom_name                   TEXT    CHECK (custom_name IS NULL OR length(custom_name) BETWEEN 1 AND 24),
  rank                          TEXT    NOT NULL CHECK (rank IN ('foreman', 'worker', 'worker2')),
  parent_dwarf_id               TEXT    REFERENCES dwarfs (id) ON DELETE SET NULL,
  delegated                     INTEGER NOT NULL DEFAULT 0 CHECK (delegated IN (0, 1)),
  profile_model                 TEXT,
  profile_effort                TEXT,
  profile_permission_mode       TEXT,
  process_state                 TEXT    NOT NULL CHECK (process_state IN ('running', 'unrecovered', 'closed')),
  presence                      TEXT    NOT NULL DEFAULT 'present' CHECK (presence IN ('present', 'resuming', 'walking-out')),
  turn_state                    TEXT    NOT NULL CHECK (turn_state IN ('active', 'ended', 'none-yet')),
  turn_ended_at                 INTEGER,
  turn_end_reliability          TEXT    CHECK (turn_end_reliability IN ('reliable', 'inferred')),
  arrived_at                    INTEGER NOT NULL,
  last_activity_at              INTEGER NOT NULL,
  workplace_path                TEXT,
  workplace_branch              TEXT,
  stop_in_flight                INTEGER NOT NULL DEFAULT 0 CHECK (stop_in_flight IN (0, 1)),
  departed_at                   INTEGER,
  departure_cause               TEXT    CHECK (departure_cause IN ('stopped', 'mine-removed', 'closed-elsewhere', 'crashed', 'recovery-dismissed', 'recovery-failed')),
  usage_path                    TEXT    NOT NULL DEFAULT 'transcript' CHECK (usage_path IN ('driver', 'transcript')),
  UNIQUE (provider_id, provider_session_id, provider_agent_id),
  CHECK ((turn_state = 'ended') = (turn_ended_at IS NOT NULL)),
  CHECK ((turn_state = 'ended') = (turn_end_reliability IS NOT NULL)),
  CHECK ((departed_at IS NULL) = (departure_cause IS NULL)),
  CHECK (departed_at IS NULL OR process_state = 'closed'),
  CHECK (workplace_branch IS NULL OR workplace_path IS NOT NULL),
  CHECK (parent_dwarf_id IS NULL OR parent_dwarf_id <> id)
) STRICT;
CREATE TABLE source_cursors (
  stream_id      TEXT    NOT NULL PRIMARY KEY CHECK (stream_id <> ''),
  adapter_id     TEXT    NOT NULL,
  kind           TEXT    NOT NULL CHECK (kind IN ('byte-offset', 'watermark', 'none')),
  value          INTEGER NOT NULL DEFAULT 0 CHECK (value >= 0),
  file_identity  TEXT,
  missing_since  INTEGER,
  updated_at     INTEGER NOT NULL,
  CHECK (kind <> 'none' OR value = 0)
) STRICT, WITHOUT ROWID;
CREATE TABLE observed_sessions (
  dwarf_id        TEXT    NOT NULL PRIMARY KEY REFERENCES dwarfs (id) ON DELETE CASCADE,
  cwd             TEXT    NOT NULL,
  first_seen_at   INTEGER NOT NULL,
  last_record_at  INTEGER NOT NULL,
  closed_at       INTEGER,
  CHECK (last_record_at >= first_seen_at)
) STRICT, WITHOUT ROWID;
CREATE TABLE observed_session_streams (
  dwarf_id   TEXT NOT NULL REFERENCES observed_sessions (dwarf_id) ON DELETE CASCADE,
  stream_id  TEXT NOT NULL REFERENCES source_cursors (stream_id) ON DELETE CASCADE,
  PRIMARY KEY (dwarf_id, stream_id)
) STRICT, WITHOUT ROWID;
CREATE TABLE ended_agents (
  provider_id          TEXT    NOT NULL,
  provider_session_id  TEXT    NOT NULL,
  provider_agent_id    TEXT    NOT NULL DEFAULT '',
  ended_at             INTEGER NOT NULL,
  PRIMARY KEY (provider_id, provider_session_id, provider_agent_id)
) STRICT, WITHOUT ROWID;
CREATE TABLE dwarf_lifecycle_facts (
  id           TEXT    NOT NULL PRIMARY KEY CHECK (length(id) = 36),
  dwarf_id     TEXT    NOT NULL REFERENCES dwarfs (id) ON DELETE CASCADE,
  type         TEXT    NOT NULL CHECK (type IN ('DwarfArrived', 'DwarfRebound', 'SubagentObserved', 'SessionClosedObserved', 'DriverSessionExited', 'TurnEnded', 'DwarfDeparted')),
  source_key   TEXT    UNIQUE,
  cause        TEXT    CHECK (cause IN ('stopped', 'mine-removed', 'closed-elsewhere', 'crashed', 'recovery-dismissed', 'recovery-failed')),
  exit_code    INTEGER,
  occurred_at  INTEGER NOT NULL,
  recorded_at  INTEGER NOT NULL,
  CHECK ((type = 'DwarfDeparted') = (cause IS NOT NULL)),
  CHECK (exit_code IS NULL OR type = 'DriverSessionExited'),
  CHECK (source_key IS NOT NULL OR type IN ('DwarfArrived', 'DwarfRebound', 'DwarfDeparted')),
  -- ADR-021 item 3 / 08 TurnEnded: once per turn whichever path reported it; the key is path-independent
  CHECK (type <> 'TurnEnded' OR source_key LIKE 'turn:%')
) STRICT;
CREATE TABLE capability_records (
  id                 TEXT    NOT NULL PRIMARY KEY CHECK (length(id) = 36),
  provider_id        TEXT    NOT NULL,
  provider_version   TEXT    NOT NULL,
  capabilities_json  TEXT    NOT NULL CHECK (json_valid(capabilities_json)),
  measured_at        INTEGER NOT NULL,
  UNIQUE (provider_id, provider_version)
) STRICT;
CREATE TABLE launches (
  id                            TEXT    NOT NULL PRIMARY KEY CHECK (length(id) = 36),
  mine_id                       TEXT    REFERENCES mines (id) ON DELETE SET NULL,
  cwd                           TEXT    NOT NULL,
  way_kind                      TEXT    NOT NULL CHECK (way_kind IN ('supplier', 'custom', 'jev')),
  provider_id                   TEXT,
  custom_command_json           TEXT    CHECK (custom_command_json IS NULL OR json_valid(custom_command_json)),
  model                         TEXT,
  effort                        TEXT,
  permission_mode               TEXT,
  launched_with_let_jev_choose  INTEGER NOT NULL CHECK (launched_with_let_jev_choose IN (0, 1)),
  jev_auto_accept               INTEGER NOT NULL DEFAULT 0 CHECK (jev_auto_accept IN (0, 1)),
  state                         TEXT    NOT NULL CHECK (state IN ('routing', 'resolving', 'spawned', 'succeeded', 'failed', 'handed-back', 'lost')),
  failure_cause                 TEXT    CHECK (failure_cause IN ('not-installed', 'exited-at-once', 'could-not-start', 'jev-unreachable', 'jev-could-not-choose')),
  jev_reason                    TEXT    CHECK (jev_reason IN ('unreachable', 'timeout', 'rate-limited', 'invalid-response', 'no-key', 'unauthorized', 'low-confidence', 'budget-exceeded', 'no-launchable-provider', 'effort-ceiling')),
  dwarf_id                      TEXT    UNIQUE REFERENCES dwarfs (id) ON DELETE SET NULL,
  retry_of                      TEXT    REFERENCES launches (id) ON DELETE SET NULL,
  delegation_id                 TEXT    REFERENCES delegations (id) ON DELETE SET NULL,
  -- set at insert and never changed: the CHECKs below read this flag, never the SET NULL FK (V4-01)
  delegated                     INTEGER NOT NULL CHECK (delegated IN (0, 1)),
  host_epoch                    TEXT    NOT NULL,
  requested_at                  INTEGER NOT NULL,
  spawned_at                    INTEGER,
  settled_at                    INTEGER,
  -- first time the launch.failed frame reached a ui connection (14 I-03); NULL = no UI saw the failure (S5.24)
  seen_at                       INTEGER,
  CHECK ((state = 'failed') = (failure_cause IS NOT NULL)),
  CHECK (seen_at IS NULL OR state = 'failed'),
  CHECK ((state IN ('succeeded', 'failed', 'handed-back', 'lost')) = (settled_at IS NOT NULL)),
  CHECK ((way_kind = 'custom') = (custom_command_json IS NOT NULL)),
  CHECK (way_kind <> 'supplier' OR provider_id IS NOT NULL),
  CHECK (delegated = 1 OR delegation_id IS NULL),
  CHECK (delegated = 0 OR launched_with_let_jev_choose = 0),
  CHECK (jev_reason IS NULL OR launched_with_let_jev_choose = 1 OR delegated = 1),
  CHECK (state <> 'handed-back' OR delegated = 0),
  CHECK (failure_cause NOT IN ('jev-unreachable', 'jev-could-not-choose') OR jev_reason IS NOT NULL)
) STRICT;
CREATE TABLE processes (
  id                     TEXT    NOT NULL PRIMARY KEY CHECK (length(id) = 36),
  pid                    INTEGER NOT NULL CHECK (pid > 0),
  process_start_time_ms  INTEGER NOT NULL,
  boot_id                TEXT    NOT NULL DEFAULT '',
  purpose                TEXT    NOT NULL CHECK (purpose IN ('session', 'session-server', 'mcp-relay', 'hook-shim', 'launcher')),
  launch_id              TEXT    REFERENCES launches (id) ON DELETE SET NULL,
  host_epoch             TEXT    NOT NULL,
  recorded_at            INTEGER NOT NULL,
  UNIQUE (pid, process_start_time_ms, boot_id)
) STRICT;
CREATE TABLE launch_records (
  dwarf_id                 TEXT    NOT NULL PRIMARY KEY REFERENCES dwarfs (id) ON DELETE CASCADE,
  launch_id                TEXT    NOT NULL UNIQUE REFERENCES launches (id) ON DELETE RESTRICT,
  driver_transport         TEXT    NOT NULL CHECK (driver_transport IN ('acp', 'agent-sdk', 'stream-json', 'app-server-rpc', 'http-server', 'ndjson', 'stdio-raw')),
  session_ref_json         TEXT    NOT NULL CHECK (json_valid(session_ref_json)),
  cwd                      TEXT    NOT NULL,
  profile_model            TEXT,
  profile_effort           TEXT,
  profile_permission_mode  TEXT,
  process_id               TEXT    REFERENCES processes (id) ON DELETE SET NULL,
  resume_intent            INTEGER NOT NULL DEFAULT 1 CHECK (resume_intent IN (0, 1)),
  stopped_by_person        INTEGER NOT NULL DEFAULT 0 CHECK (stopped_by_person IN (0, 1)),
  host_epoch               TEXT    NOT NULL,
  ended_at                 INTEGER,
  CHECK (ended_at IS NULL OR resume_intent = 0)
) STRICT, WITHOUT ROWID;
CREATE TABLE host_recovery_reports (
  host_epoch    TEXT    NOT NULL PRIMARY KEY,
  at            INTEGER NOT NULL,
  resumed_json  TEXT    NOT NULL DEFAULT '[]' CHECK (json_valid(resumed_json)),
  state         TEXT    NOT NULL DEFAULT 'pending-display' CHECK (state IN ('pending-display', 'shown', 'retrying', 'settled', 'superseded')),
  shown_at      INTEGER,
  settled_at    INTEGER,
  CHECK ((state = 'settled') = (settled_at IS NOT NULL)),
  CHECK (state NOT IN ('shown', 'retrying', 'settled') OR shown_at IS NOT NULL)
) STRICT, WITHOUT ROWID;
CREATE TABLE host_recovery_items (
  host_epoch        TEXT NOT NULL REFERENCES host_recovery_reports (host_epoch) ON DELETE CASCADE,
  dwarf_id          TEXT NOT NULL REFERENCES dwarfs (id) ON DELETE CASCADE,
  reason            TEXT NOT NULL CHECK (reason IN ('turn-lost', 'no-resume', 'stale-ref', 'resume-error', 'end-failed')),
  message_ids_json  TEXT CHECK (message_ids_json IS NULL OR json_valid(message_ids_json)),
  retry_outcome     TEXT CHECK (retry_outcome IN ('resumed', 'failed')),
  PRIMARY KEY (host_epoch, dwarf_id)
) STRICT, WITHOUT ROWID;
CREATE TABLE messages (
  id                TEXT    NOT NULL PRIMARY KEY CHECK (length(id) = 36),
  dwarf_id          TEXT    NOT NULL REFERENCES dwarfs (id) ON DELETE CASCADE,
  source_key        TEXT    UNIQUE,
  role              TEXT    NOT NULL CHECK (role IN ('person', 'dwarf', 'answers-record', 'system-line')),
  text              TEXT    NOT NULL CHECK (length(CAST(text AS BLOB)) <= 65536),
  issuer_dwarf_id   TEXT    REFERENCES dwarfs (id) ON DELETE SET NULL,
  activity_json     TEXT    CHECK (activity_json IS NULL OR json_valid(activity_json)),
  attachments_json  TEXT    NOT NULL DEFAULT '[]' CHECK (json_valid(attachments_json)),
  origin            TEXT    NOT NULL CHECK (origin IN ('live-stream', 'transcript', 'dwarfai')),
  pending_echo      TEXT,
  provider_time     INTEGER,
  created_at        INTEGER NOT NULL,
  ask_id            TEXT    REFERENCES asks (id) ON DELETE SET NULL,
  -- transport requestId of the conversation.send that created this row (14 §1.6 durable dedupe); NULL for every other row
  request_id        TEXT,
  sort_at           INTEGER GENERATED ALWAYS AS (coalesce(provider_time, created_at)) STORED,
  CHECK (source_key IS NOT NULL OR origin = 'dwarfai'),
  CHECK (request_id IS NULL OR (role = 'person' AND origin = 'dwarfai')),
  CHECK (pending_echo IS NULL OR origin = 'dwarfai'),
  CHECK (role <> 'answers-record' OR origin = 'dwarfai'),
  CHECK (ask_id IS NULL OR role = 'answers-record'),
  CHECK (issuer_dwarf_id IS NULL OR issuer_dwarf_id <> dwarf_id)
) STRICT;
CREATE TABLE message_keys (
  source_key     TEXT    NOT NULL PRIMARY KEY,
  dwarf_id       TEXT    NOT NULL REFERENCES dwarfs (id) ON DELETE CASCADE,
  message_id     TEXT    REFERENCES messages (id) ON DELETE SET NULL,
  first_seen_at  INTEGER NOT NULL
) STRICT, WITHOUT ROWID;
CREATE TABLE deliveries (
  message_id           TEXT    NOT NULL PRIMARY KEY REFERENCES messages (id) ON DELETE CASCADE,
  dwarf_id             TEXT    NOT NULL REFERENCES dwarfs (id) ON DELETE CASCADE,
  kind                 TEXT    NOT NULL CHECK (kind IN ('message', 'answers-record')),
  phase                TEXT    NOT NULL CHECK (phase IN ('sending', 'delivered', 'reacted', 'failed')),
  confidence           TEXT    CHECK (confidence IN ('confirmed', 'unconfirmed')),
  held_until_turn_end  INTEGER NOT NULL DEFAULT 0 CHECK (held_until_turn_end IN (0, 1)),
  failure_kind         TEXT    CHECK (failure_kind IN ('channel-error', 'session-closed', 'refused', 'host-interrupted')),
  failure_reason       TEXT,
  attempts             INTEGER NOT NULL DEFAULT 1 CHECK (attempts >= 1),
  sent_at              INTEGER NOT NULL,
  phase_at             INTEGER NOT NULL,
  CHECK ((phase = 'failed') = (failure_kind IS NOT NULL)),
  CHECK (confidence IS NULL OR phase IN ('delivered', 'reacted')),
  CHECK (failure_kind <> 'refused' OR (kind = 'answers-record' AND failure_reason IN ('channel-rejected', 'invalid-answer', 'channel-unavailable', 'ask-closed'))),
  CHECK (failure_kind NOT IN ('session-closed', 'host-interrupted') OR failure_reason IS NULL)
) STRICT, WITHOUT ROWID;
CREATE TABLE activity_disclosures (
  id              TEXT    NOT NULL PRIMARY KEY CHECK (length(id) = 36),
  dwarf_id        TEXT    NOT NULL REFERENCES dwarfs (id) ON DELETE CASCADE,
  turn_key        TEXT    NOT NULL,
  open            INTEGER NOT NULL CHECK (open IN (0, 1)),
  step_count      INTEGER NOT NULL DEFAULT 0 CHECK (step_count >= 0),
  summaries_json  TEXT    NOT NULL DEFAULT '[]' CHECK (json_valid(summaries_json)),
  opened_at       INTEGER NOT NULL,
  closed_at       INTEGER,
  UNIQUE (dwarf_id, turn_key),
  CHECK ((open = 1) = (closed_at IS NULL))
) STRICT;
CREATE TABLE outcome_lines (
  dwarf_id       TEXT    NOT NULL PRIMARY KEY REFERENCES dwarfs (id) ON DELETE CASCADE,
  kind           TEXT    NOT NULL,
  step_count     INTEGER NOT NULL DEFAULT 0 CHECK (step_count >= 0),
  parts_json     TEXT    NOT NULL DEFAULT '[]' CHECK (json_valid(parts_json) AND json_array_length(parts_json) <= 3),
  detail         TEXT,
  closing_words  TEXT,
  reliability    TEXT    NOT NULL CHECK (reliability IN ('reliable', 'inferred')),
  at             INTEGER NOT NULL
) STRICT, WITHOUT ROWID;
CREATE TABLE asks (
  id                   TEXT    NOT NULL PRIMARY KEY CHECK (length(id) = 36),
  dwarf_id             TEXT    NOT NULL REFERENCES dwarfs (id) ON DELETE CASCADE,
  kind                 TEXT    NOT NULL CHECK (kind IN ('question', 'permission')),
  channel              TEXT    NOT NULL CHECK (channel IN ('driver', 'hook-keystroke', 'hook-decision', 'http', 'none')),
  provider_request_id  TEXT    NOT NULL,
  payload_json         TEXT    NOT NULL CHECK (json_valid(payload_json)),
  current_step         INTEGER NOT NULL DEFAULT 0 CHECK (current_step >= 0),
  state                TEXT    NOT NULL CHECK (state IN ('open', 'answering', 'answered-in-app', 'answered-elsewhere', 'cancelled', 'closed-by-death', 'auto-denied')),
  reannounce           INTEGER NOT NULL DEFAULT 1 CHECK (reannounce IN (0, 1)),
  opened_at            INTEGER NOT NULL,
  closed_at            INTEGER,
  UNIQUE (dwarf_id, provider_request_id),
  CHECK ((state IN ('open', 'answering')) = (closed_at IS NULL)),
  CHECK (channel <> 'none' OR state NOT IN ('answering', 'answered-in-app'))
) STRICT;
CREATE TABLE ask_answers (
  request_id      TEXT    NOT NULL PRIMARY KEY,
  ask_id          TEXT    NOT NULL REFERENCES asks (id) ON DELETE CASCADE,
  outcome         TEXT    CHECK (outcome IN ('accepted', 'refused')),
  refusal_reason  TEXT    CHECK (refusal_reason IN ('channel-rejected', 'invalid-answer', 'channel-unavailable', 'ask-closed')),
  message_id      TEXT    REFERENCES messages (id) ON DELETE SET NULL,
  at              INTEGER NOT NULL,
  settled_at      INTEGER,
  CHECK ((outcome = 'refused') = (refusal_reason IS NOT NULL)),
  CHECK (outcome IS NOT NULL OR refusal_reason IS NULL),
  CHECK ((outcome IS NULL) = (settled_at IS NULL))
) STRICT, WITHOUT ROWID;
CREATE TABLE attention_keys (
  key            TEXT    NOT NULL PRIMARY KEY,
  dwarf_id       TEXT    NOT NULL REFERENCES dwarfs (id) ON DELETE CASCADE,
  kind           TEXT    NOT NULL CHECK (kind IN ('question', 'permission', 'turn-finished')),
  ask_id         TEXT    REFERENCES asks (id) ON DELETE CASCADE,
  host_epoch     TEXT    NOT NULL,
  emitted_at     INTEGER NOT NULL,
  suppressed     INTEGER NOT NULL DEFAULT 0 CHECK (suppressed IN (0, 1)),
  withdrawn_at   INTEGER,
  -- an ask key names its ask; a turn key has none
  CHECK ((kind = 'turn-finished') = (ask_id IS NULL))
) STRICT, WITHOUT ROWID;
CREATE TABLE attention_announced (
  dwarf_id       TEXT    NOT NULL REFERENCES dwarfs (id) ON DELETE CASCADE,
  kind           TEXT    NOT NULL CHECK (kind IN ('question', 'permission')),
  pre_crash_key  TEXT    NOT NULL,
  host_epoch     TEXT    NOT NULL,
  recorded_at    INTEGER NOT NULL,
  PRIMARY KEY (dwarf_id, kind)
) STRICT, WITHOUT ROWID;
CREATE TABLE delegations (
  id               TEXT    NOT NULL PRIMARY KEY CHECK (length(id) = 36),
  parent_dwarf_id  TEXT    NOT NULL REFERENCES dwarfs (id) ON DELETE CASCADE,
  worker_dwarf_id  TEXT    UNIQUE REFERENCES dwarfs (id) ON DELETE SET NULL,
  ticket           TEXT    NOT NULL UNIQUE,
  task_text        TEXT    CHECK (task_text IS NULL OR length(task_text) <= 4000),
  context_text     TEXT    CHECK (context_text IS NULL OR length(context_text) <= 16000),
  state            TEXT    NOT NULL CHECK (state IN ('attempted', 'running', 'succeeded', 'failed')),
  failure          TEXT    CHECK (failure IN ('gate-closed', 'jev-unreachable', 'jev-could-not-choose', 'no-provider', 'worker-failed', 'worker-lost', 'handoff-failed', 'parent-gone')),
  handoff_via      TEXT    CHECK (handoff_via IN ('tool-result', 'turn-input')),
  handoff_phase    TEXT    CHECK (handoff_phase IN ('sending', 'delivered', 'failed')),
  handoff_phase_at INTEGER,
  created_at       INTEGER NOT NULL,
  settled_at       INTEGER,
  CHECK ((state = 'failed') = (failure IS NOT NULL)),
  CHECK ((state IN ('succeeded', 'failed')) = (settled_at IS NOT NULL)),
  -- Delegation.handoff (06): the three fields together; the result text itself is never stored (PO #19, PO #87)
  CHECK ((handoff_via IS NULL) = (handoff_phase IS NULL) AND (handoff_phase IS NULL) = (handoff_phase_at IS NULL)),
  CHECK (state <> 'succeeded' OR handoff_phase IS 'delivered'),
  CHECK (state IN ('attempted', 'running') OR (task_text IS NULL AND context_text IS NULL)),
  CHECK (worker_dwarf_id IS NULL OR worker_dwarf_id <> parent_dwarf_id)
) STRICT;
CREATE TABLE delegation_tokens (
  launch_id          TEXT    NOT NULL PRIMARY KEY REFERENCES launches (id) ON DELETE CASCADE,
  parent_dwarf_id    TEXT    NOT NULL REFERENCES dwarfs (id) ON DELETE CASCADE,
  mechanism          TEXT    NOT NULL CHECK (mechanism IN ('in-process', 'protocol', 'ticket-file')),
  credential_hash    TEXT    CHECK (credential_hash IS NULL OR length(credential_hash) = 64),
  issued_at          INTEGER NOT NULL,
  revoked_at         INTEGER,
  CHECK ((mechanism = 'ticket-file') = (credential_hash IS NOT NULL))
) STRICT, WITHOUT ROWID;
CREATE TABLE usage_units (
  unit_key           TEXT    NOT NULL PRIMARY KEY,
  dwarf_id           TEXT    NOT NULL REFERENCES dwarfs (id) ON DELETE CASCADE,
  mine_id            TEXT    NOT NULL REFERENCES mines (id) ON DELETE CASCADE,
  sealed             INTEGER NOT NULL DEFAULT 0 CHECK (sealed IN (0, 1)),
  provider_time      INTEGER,
  first_observed_at  INTEGER NOT NULL,
  sealed_at          INTEGER,
  CHECK ((sealed = 1) = (sealed_at IS NOT NULL))
) STRICT, WITHOUT ROWID;
CREATE TABLE usage_observations (
  source_key     TEXT    NOT NULL PRIMARY KEY,
  unit_key       TEXT    NOT NULL REFERENCES usage_units (unit_key) ON DELETE CASCADE,
  path           TEXT    NOT NULL CHECK (path IN ('driver', 'transcript')),
  fidelity       INTEGER NOT NULL CHECK (fidelity IN (0, 1, 2)),
  input_net      INTEGER NOT NULL DEFAULT 0 CHECK (input_net >= 0),
  output         INTEGER NOT NULL DEFAULT 0 CHECK (output >= 0),
  cache_read     INTEGER NOT NULL DEFAULT 0 CHECK (cache_read >= 0),
  cache_write    INTEGER NOT NULL DEFAULT 0 CHECK (cache_write >= 0),
  reasoning      INTEGER NOT NULL DEFAULT 0 CHECK (reasoning >= 0),
  sealed         INTEGER NOT NULL DEFAULT 0 CHECK (sealed IN (0, 1)),
  provider_time  INTEGER,
  observed_at    INTEGER NOT NULL
) STRICT, WITHOUT ROWID;
CREATE TABLE ledger_entries (
  id           TEXT    NOT NULL PRIMARY KEY CHECK (length(id) = 36),
  unit_key     TEXT    NOT NULL UNIQUE,
  mine_id      TEXT    NOT NULL REFERENCES mines (id) ON DELETE CASCADE,
  material     TEXT    NOT NULL CHECK (material IN ('coal', 'bronze', 'copper', 'silver', 'gold', 'uranium')),
  tokens       INTEGER NOT NULL CHECK (tokens >= 0),
  units        INTEGER NOT NULL CHECK (units >= 0),
  kind         TEXT    NOT NULL CHECK (kind IN ('live', 'coal-backfill')),
  source_key   TEXT,
  credited_at  INTEGER NOT NULL,
  -- invariant 6 (DWARFAI_ARQUITECTURA_DATOS §6a, ledger.ts:224): coal only via the backfill, and the backfill pays only coal
  CHECK ((kind = 'coal-backfill') = (material = 'coal'))
) STRICT;
CREATE TABLE material_totals (
  mine_id   TEXT    NOT NULL REFERENCES mines (id) ON DELETE CASCADE,
  material  TEXT    NOT NULL CHECK (material IN ('coal', 'bronze', 'copper', 'silver', 'gold', 'uranium')),
  tokens    INTEGER NOT NULL DEFAULT 0 CHECK (tokens >= 0),
  units     INTEGER NOT NULL DEFAULT 0 CHECK (units >= 0),
  PRIMARY KEY (mine_id, material)
) STRICT, WITHOUT ROWID;
CREATE TABLE host_preferences (
  id                       INTEGER NOT NULL PRIMARY KEY CHECK (id = 1),
  subagent_delegation_on   INTEGER NOT NULL DEFAULT 0 CHECK (subagent_delegation_on IN (0, 1)),
  routing_profile          TEXT    NOT NULL DEFAULT 'balanced' CHECK (routing_profile IN ('economy', 'balanced', 'premium')),
  default_provider         TEXT,
  default_model            TEXT,
  default_effort           TEXT,
  system_notifications_on  INTEGER NOT NULL DEFAULT 1 CHECK (system_notifications_on IN (0, 1)),
  updated_at               INTEGER NOT NULL,
  CHECK (default_provider IS NOT NULL OR (default_model IS NULL AND default_effort IS NULL))
) STRICT;
CREATE TABLE integration_settings (
  id              TEXT    NOT NULL PRIMARY KEY CHECK (id IN ('opencode-permissions', 'claude-hooks')),
  state           TEXT    NOT NULL DEFAULT 'off' CHECK (state IN ('off', 'on-unverified', 'on-verified')),
  consent_origin  TEXT    CHECK (consent_origin IN ('settings', 'add-panel', 'first-run')),   -- 'first-run' AMENDMENT-7 (OQ-68)
  changed_at      INTEGER NOT NULL,
  CHECK ((state = 'off') = (consent_origin IS NULL)),
  CHECK (id = 'opencode-permissions' OR consent_origin IS NULL OR consent_origin IN ('settings', 'first-run'))
) STRICT, WITHOUT ROWID;
CREATE TABLE config_writes (
  id              TEXT    NOT NULL PRIMARY KEY CHECK (length(id) = 36),
  target_path     TEXT    NOT NULL,
  kind            TEXT    NOT NULL CHECK (kind IN ('claude-hooks', 'opencode-plugin')),
  owned_marker    TEXT    NOT NULL,
  backup_path     TEXT,
  consent_origin  TEXT    NOT NULL CHECK (consent_origin IN ('settings', 'add-panel', 'first-run')),   -- 'first-run' AMENDMENT-7
  written_at      INTEGER NOT NULL,
  verified_at     INTEGER,
  reverted_at     INTEGER,
  CHECK (kind = 'opencode-plugin' OR consent_origin IN ('settings', 'first-run'))
) STRICT;
CREATE TABLE channel_tokens (
  id            TEXT    NOT NULL PRIMARY KEY CHECK (length(id) = 36),
  channel       TEXT    NOT NULL CHECK (channel IN ('claude-hooks', 'opencode-plugin')),
  token_sha256  TEXT    NOT NULL UNIQUE CHECK (length(token_sha256) = 64),
  created_at    INTEGER NOT NULL,
  revoked_at    INTEGER
) STRICT;
INSERT INTO "schema_migrations" ("version", "name", "checksum", "applied_at", "app_version") VALUES (1, '0001-initial', '66f0966f7fb127f2296b7991604693f1f34d2b5d49665b5445cc8584eea6ea61', 1750000000000, 'cut-0');
INSERT INTO "app_meta" ("id", "install_id", "reset_epoch", "current_host_epoch", "host_epoch_started_at", "host_boot_id", "host_boot_time_ms", "host_logon_session_id", "clean_shutdown_epoch", "clean_shutdown_at", "clean_shutdown_reason", "ingress_port", "welcome_answered_at", "created_at") VALUES (1, '00000000-0000-7000-8000-000000000001', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1750000000000);
INSERT INTO "install_moment" ("id", "at", "reason", "backfill_state", "backfill_done_at") VALUES (1, 1750000000000, 'fresh-install', 'not-started', NULL);
INSERT INTO "mines" ("id", "canonical_path", "name", "name_norm", "state", "tier", "source_weight_bytes", "has_been_measured", "measured_at", "unenterable_reason", "removed_at", "created_at", "last_used_at", "map_site_x_pct", "map_site_y_pct") VALUES ('00000000-0000-7000-8000-00000000c0f1', '/work/mine-one', 'mine-one', 'mine-one', 'active', 'bronze', 524288, 1, 1750000001000, NULL, NULL, 1750000000000, 1750000060000, NULL, NULL);
INSERT INTO "dwarfs" ("id", "mine_id", "provider_id", "provider_session_id", "provider_agent_id", "previous_provider_session_id", "base_name", "custom_name", "rank", "parent_dwarf_id", "delegated", "profile_model", "profile_effort", "profile_permission_mode", "process_state", "presence", "turn_state", "turn_ended_at", "turn_end_reliability", "arrived_at", "last_activity_at", "workplace_path", "workplace_branch", "stop_in_flight", "departed_at", "departure_cause", "usage_path") VALUES ('00000000-0000-7000-8000-00000000c0d1', '00000000-0000-7000-8000-00000000c0f1', 'claude', 'session-c0-1', '', NULL, 'Durin', NULL, 'foreman', NULL, 0, NULL, NULL, NULL, 'running', 'present', 'ended', 1750000050000, 'reliable', 1750000002000, 1750000050000, '/work/mine-one', NULL, 0, NULL, NULL, 'transcript');
INSERT INTO "source_cursors" ("stream_id", "adapter_id", "kind", "value", "file_identity", "missing_since", "updated_at") VALUES ('claude:session-c0-1', 'claude-transcript', 'byte-offset', 2048, NULL, NULL, 1750000050000);
INSERT INTO "observed_sessions" ("dwarf_id", "cwd", "first_seen_at", "last_record_at", "closed_at") VALUES ('00000000-0000-7000-8000-00000000c0d1', '/work/mine-one', 1750000002000, 1750000050000, NULL);
INSERT INTO "observed_session_streams" ("dwarf_id", "stream_id") VALUES ('00000000-0000-7000-8000-00000000c0d1', 'claude:session-c0-1');
INSERT INTO "dwarf_lifecycle_facts" ("id", "dwarf_id", "type", "source_key", "cause", "exit_code", "occurred_at", "recorded_at") VALUES ('00000000-0000-7000-8000-00000000c0e1', '00000000-0000-7000-8000-00000000c0d1', 'DwarfArrived', NULL, NULL, NULL, 1750000002000, 1750000002000);
INSERT INTO "messages" ("id", "dwarf_id", "source_key", "role", "text", "issuer_dwarf_id", "activity_json", "attachments_json", "origin", "pending_echo", "provider_time", "created_at", "ask_id", "request_id") VALUES ('00000000-0000-7000-8000-00000000c0a1', '00000000-0000-7000-8000-00000000c0d1', NULL, 'person', 'Please add the README section.', NULL, NULL, '[]', 'dwarfai', NULL, NULL, 1750000010000, NULL, 'req-c0-1');
INSERT INTO "messages" ("id", "dwarf_id", "source_key", "role", "text", "issuer_dwarf_id", "activity_json", "attachments_json", "origin", "pending_echo", "provider_time", "created_at", "ask_id", "request_id") VALUES ('00000000-0000-7000-8000-00000000c0a2', '00000000-0000-7000-8000-00000000c0d1', 'claude:session-c0-1:msg-2', 'dwarf', 'On it.', NULL, NULL, '[]', 'transcript', NULL, 1750000011000, 1750000011200, NULL, NULL);
INSERT INTO "messages" ("id", "dwarf_id", "source_key", "role", "text", "issuer_dwarf_id", "activity_json", "attachments_json", "origin", "pending_echo", "provider_time", "created_at", "ask_id", "request_id") VALUES ('00000000-0000-7000-8000-00000000c0a3', '00000000-0000-7000-8000-00000000c0d1', 'claude:session-c0-1:msg-3', 'dwarf', 'Added the section.' || char(10) || 'It''s under "Usage".', NULL, NULL, '[]', 'transcript', NULL, 1750000049000, 1750000049300, NULL, NULL);
INSERT INTO "message_keys" ("source_key", "dwarf_id", "message_id", "first_seen_at") VALUES ('claude:session-c0-1:msg-2', '00000000-0000-7000-8000-00000000c0d1', '00000000-0000-7000-8000-00000000c0a2', 1750000011200);
INSERT INTO "message_keys" ("source_key", "dwarf_id", "message_id", "first_seen_at") VALUES ('claude:session-c0-1:msg-3', '00000000-0000-7000-8000-00000000c0d1', '00000000-0000-7000-8000-00000000c0a3', 1750000049300);
INSERT INTO "deliveries" ("message_id", "dwarf_id", "kind", "phase", "confidence", "held_until_turn_end", "failure_kind", "failure_reason", "attempts", "sent_at", "phase_at") VALUES ('00000000-0000-7000-8000-00000000c0a1', '00000000-0000-7000-8000-00000000c0d1', 'message', 'delivered', 'confirmed', 0, NULL, NULL, 1, 1750000010000, 1750000010500);
INSERT INTO "usage_units" ("unit_key", "dwarf_id", "mine_id", "sealed", "provider_time", "first_observed_at", "sealed_at") VALUES ('claude:session-c0-1:msg-2', '00000000-0000-7000-8000-00000000c0d1', '00000000-0000-7000-8000-00000000c0f1', 1, 1750000011000, 1750000011200, 1750000012000);
INSERT INTO "usage_observations" ("source_key", "unit_key", "path", "fidelity", "input_net", "output", "cache_read", "cache_write", "reasoning", "sealed", "provider_time", "observed_at") VALUES ('claude:session-c0-1:msg-2:usage', 'claude:session-c0-1:msg-2', 'transcript', 2, 1000, 200, 4000, 0, 0, 1, 1750000011000, 1750000011200);
INSERT INTO "ledger_entries" ("id", "unit_key", "mine_id", "material", "tokens", "units", "kind", "source_key", "credited_at") VALUES ('00000000-0000-7000-8000-00000000c0b1', 'claude:session-c0-1:msg-2', '00000000-0000-7000-8000-00000000c0f1', 'bronze', 1200, 1, 'live', 'claude:session-c0-1:msg-2:usage', 1750000012000);
INSERT INTO "material_totals" ("mine_id", "material", "tokens", "units") VALUES ('00000000-0000-7000-8000-00000000c0f1', 'bronze', 1200, 1);
INSERT INTO "host_preferences" ("id", "subagent_delegation_on", "routing_profile", "default_provider", "default_model", "default_effort", "system_notifications_on", "updated_at") VALUES (1, 0, 'balanced', NULL, NULL, NULL, 1, 1750000000000);
INSERT INTO "integration_settings" ("id", "state", "consent_origin", "changed_at") VALUES ('claude-hooks', 'off', NULL, 1750000000000);
INSERT INTO "integration_settings" ("id", "state", "consent_origin", "changed_at") VALUES ('opencode-permissions', 'off', NULL, 1750000000000);
CREATE INDEX coal_backfill_units_moment ON coal_backfill_units (install_moment_id);
CREATE UNIQUE INDEX reset_journal_one_active ON reset_journal ((step = 'done')) WHERE step <> 'done';
CREATE INDEX mines_name_norm ON mines (name_norm);
CREATE INDEX mines_last_used ON mines (last_used_at DESC) WHERE removed_at IS NULL;
CREATE INDEX dwarfs_mine ON dwarfs (mine_id, arrived_at);
CREATE INDEX dwarfs_crew ON dwarfs (mine_id) WHERE departed_at IS NULL;
CREATE INDEX dwarfs_parent ON dwarfs (parent_dwarf_id) WHERE parent_dwarf_id IS NOT NULL;
CREATE INDEX dwarfs_previous_session ON dwarfs (provider_id, previous_provider_session_id) WHERE previous_provider_session_id IS NOT NULL;
CREATE INDEX source_cursors_adapter ON source_cursors (adapter_id);
CREATE INDEX source_cursors_missing ON source_cursors (missing_since) WHERE missing_since IS NOT NULL;
CREATE INDEX observed_session_streams_stream ON observed_session_streams (stream_id);
CREATE INDEX dwarf_lifecycle_facts_dwarf ON dwarf_lifecycle_facts (dwarf_id, occurred_at);
CREATE UNIQUE INDEX dwarf_lifecycle_facts_one_departure ON dwarf_lifecycle_facts (dwarf_id) WHERE type = 'DwarfDeparted';
CREATE INDEX capability_records_latest ON capability_records (provider_id, measured_at DESC);
CREATE INDEX launches_mine ON launches (mine_id);
CREATE INDEX launches_retry_of ON launches (retry_of) WHERE retry_of IS NOT NULL;
CREATE INDEX launches_delegation ON launches (delegation_id) WHERE delegation_id IS NOT NULL;
CREATE INDEX launches_in_flight ON launches (requested_at) WHERE state IN ('routing', 'resolving', 'spawned');
CREATE INDEX launches_settled ON launches (settled_at) WHERE settled_at IS NOT NULL;
CREATE INDEX processes_launch ON processes (launch_id) WHERE launch_id IS NOT NULL;
CREATE INDEX processes_epoch ON processes (host_epoch, purpose);
CREATE INDEX launch_records_process ON launch_records (process_id) WHERE process_id IS NOT NULL;
CREATE INDEX launch_records_live ON launch_records (host_epoch) WHERE ended_at IS NULL;
CREATE INDEX host_recovery_items_dwarf ON host_recovery_items (dwarf_id);
CREATE INDEX messages_feed ON messages (dwarf_id, sort_at DESC, id DESC);
CREATE INDEX messages_pending_echo ON messages (dwarf_id, pending_echo) WHERE pending_echo IS NOT NULL;
CREATE INDEX messages_issuer ON messages (issuer_dwarf_id) WHERE issuer_dwarf_id IS NOT NULL;
CREATE UNIQUE INDEX messages_one_record_per_ask ON messages (ask_id) WHERE ask_id IS NOT NULL;
CREATE UNIQUE INDEX messages_send_request ON messages (request_id) WHERE request_id IS NOT NULL;
CREATE INDEX message_keys_dwarf ON message_keys (dwarf_id);
CREATE INDEX message_keys_message ON message_keys (message_id) WHERE message_id IS NOT NULL;
CREATE INDEX deliveries_dwarf_open ON deliveries (dwarf_id, phase) WHERE phase IN ('sending', 'delivered');
CREATE INDEX deliveries_dwarf ON deliveries (dwarf_id);
CREATE UNIQUE INDEX activity_disclosures_one_open ON activity_disclosures (dwarf_id) WHERE open = 1;
CREATE UNIQUE INDEX asks_one_answering ON asks (dwarf_id) WHERE state = 'answering';
CREATE INDEX asks_live ON asks (dwarf_id, opened_at) WHERE state IN ('open', 'answering');
CREATE INDEX asks_needs_you ON asks (opened_at) WHERE state IN ('open', 'answering');
CREATE INDEX asks_closed ON asks (closed_at) WHERE closed_at IS NOT NULL;
CREATE INDEX ask_answers_ask ON ask_answers (ask_id);
CREATE INDEX ask_answers_message ON ask_answers (message_id) WHERE message_id IS NOT NULL;
CREATE INDEX attention_keys_dwarf ON attention_keys (dwarf_id, kind);
CREATE INDEX attention_keys_ask ON attention_keys (ask_id) WHERE ask_id IS NOT NULL;
CREATE INDEX attention_keys_withdrawn ON attention_keys (withdrawn_at) WHERE withdrawn_at IS NOT NULL;
CREATE INDEX delegations_parent ON delegations (parent_dwarf_id);
CREATE INDEX delegations_in_flight ON delegations (created_at) WHERE state IN ('attempted', 'running');
CREATE INDEX delegation_tokens_parent ON delegation_tokens (parent_dwarf_id);
CREATE INDEX usage_units_dwarf ON usage_units (dwarf_id);
CREATE INDEX usage_units_mine_sealed ON usage_units (mine_id, sealed);
CREATE INDEX usage_units_sealed_at ON usage_units (sealed_at) WHERE sealed = 1;
CREATE INDEX usage_observations_unit ON usage_observations (unit_key, fidelity DESC, observed_at ASC);
CREATE INDEX ledger_entries_mine ON ledger_entries (mine_id, material);
CREATE UNIQUE INDEX config_writes_one_active ON config_writes (kind, target_path) WHERE reverted_at IS NULL;
CREATE INDEX config_writes_reverted ON config_writes (reverted_at) WHERE reverted_at IS NOT NULL;
CREATE UNIQUE INDEX channel_tokens_one_active ON channel_tokens (channel) WHERE revoked_at IS NULL;
CREATE INDEX channel_tokens_revoked ON channel_tokens (revoked_at) WHERE revoked_at IS NOT NULL;
CREATE TRIGGER source_cursors_never_regress
BEFORE UPDATE OF value, kind ON source_cursors
WHEN NEW.value < OLD.value OR NEW.kind <> OLD.kind
BEGIN
  SELECT RAISE(ABORT, 'CURSOR_REGRESSION');
END;
CREATE TRIGGER deliveries_match_message
BEFORE INSERT ON deliveries
WHEN NOT EXISTS (
  SELECT 1 FROM messages m
   WHERE m.id = NEW.message_id
     AND m.dwarf_id = NEW.dwarf_id
     AND ((NEW.kind = 'answers-record') = (m.role = 'answers-record'))
     AND m.role IN ('person', 'answers-record')
)
BEGIN
  SELECT RAISE(ABORT, 'DELIVERY_MESSAGE_MISMATCH');
END;
CREATE TRIGGER deliveries_match_message_update
BEFORE UPDATE OF message_id, dwarf_id, kind ON deliveries
WHEN NEW.message_id <> OLD.message_id OR NEW.dwarf_id <> OLD.dwarf_id OR NEW.kind <> OLD.kind
BEGIN
  SELECT RAISE(ABORT, 'DELIVERY_MESSAGE_MISMATCH');
END;
CREATE TRIGGER ledger_entries_accumulate
AFTER INSERT ON ledger_entries
BEGIN
  INSERT INTO material_totals (mine_id, material, tokens, units)
  VALUES (NEW.mine_id, NEW.material, NEW.tokens, NEW.units)
  ON CONFLICT (mine_id, material) DO UPDATE
    SET tokens = tokens + excluded.tokens,
        units  = units + excluded.units;
END;
CREATE TRIGGER ledger_entries_withdraw
AFTER DELETE ON ledger_entries
BEGIN
  UPDATE material_totals
     SET tokens = tokens - OLD.tokens,
         units  = units - OLD.units
   WHERE mine_id = OLD.mine_id AND material = OLD.material;
END;
CREATE TRIGGER ledger_entries_immutable
BEFORE UPDATE ON ledger_entries
BEGIN
  SELECT RAISE(ABORT, 'LEDGER_ENTRY_IMMUTABLE');
END;
PRAGMA application_id = 1146569033;
COMMIT;
