// GENERATED by `pnpm ipc:generate` (scripts/ipc/generate-window-api.mjs) — do not edit by hand (22 §5).
// The fake `window.api` for renderer tests (ADR-033 item 7; 17 §1.6). Never imported by production code (R14).
// Source: the channel registry (src/contracts/ipc) and the route table's shapes (src/ui-main/ipc/routes.ts).
import type { DwarfAiMinersApi } from '../../../preload/index'

export type WindowApiMemberKind = 'invoke' | 'send' | 'push' | 'helper'

/** Every member of `window.api` with its kind: exactly the registry's rows. */
export const WINDOW_API_MEMBERS = {
  hidePanel: 'send',
  raisePanel: 'send',
  getAlwaysOnTop: 'invoke',
  setAlwaysOnTop: 'invoke',
  getPanelVisible: 'invoke',
  getAudioPreferences: 'invoke',
  setAudioPreferences: 'invoke',
  getPanelLayout: 'invoke',
  setPanelLayout: 'invoke',
  getToggleShortcut: 'invoke',
  setToggleShortcut: 'invoke',
  getMines: 'invoke',
  activateDwarf: 'invoke',
  getDwarfFeed: 'invoke',
  getDwarfFeedPage: 'invoke',
  setWatchedDwarf: 'send',
  refreshDwarfTelemetry: 'send',
  setDwarfTuning: 'invoke',
  getMineHistory: 'invoke',
  openMinePath: 'invoke',
  openExternalLink: 'invoke',
  copyText: 'invoke',
  sendDwarfText: 'invoke',
  chooseDwarfAttachments: 'invoke',
  describeDwarfAttachments: 'invoke',
  kickDwarf: 'invoke',
  retireDwarf: 'send',
  getAppBuild: 'invoke',
  getFeatureFlags: 'invoke',
  declareMine: 'invoke',
  declareMainProject: 'invoke',
  undeclareMine: 'invoke',
  resetMetrics: 'invoke',
  queryProjects: 'invoke',
  launchAgent: 'invoke',
  listAgentProviders: 'invoke',
  listAgentModels: 'invoke',
  launchHeldSession: 'invoke',
  launchHostedProcess: 'invoke',
  answerDwarfQuestion: 'invoke',
  answerDwarfPermission: 'invoke',
  getNotificationsEnabled: 'invoke',
  setNotificationsEnabled: 'invoke',
  setOpenMine: 'send',
  getTypographyPreferences: 'invoke',
  setTypographyPreferences: 'invoke',
  getJevSettings: 'invoke',
  setJevApiKey: 'invoke',
  clearJevApiKey: 'invoke',
  routeJevLaunch: 'invoke',
  setJevPreferences: 'invoke',
  getOpenCodeSettings: 'invoke',
  setOpenCodePluginEnabled: 'invoke',
  setOpenCodeServerPassword: 'invoke',
  clearOpenCodeServerPassword: 'invoke',
  getLaunchView: 'invoke',
  setLaunchView: 'send',
  onPanelVisibility: 'push',
  onMinesUpdated: 'push',
  onLaunchFailed: 'push',
  onDwarfSendSettled: 'push',
  onShowMine: 'push',
  onTypographyPreferences: 'push',
  pathForDroppedFile: 'helper',
  setDwarfName: 'invoke',
  resetDwarfName: 'invoke',
  reportRendererDiagnostic: 'send',
  onStopEverythingRequested: 'push',
  confirmStopEverything: 'invoke',
  cancelStopEverything: 'send',
  requestStopEverything: 'send',
  getHostConnection: 'invoke',
  onHostConnection: 'push',
  retryHostConnection: 'invoke',
  confirmHostRestart: 'invoke',
  getUiSession: 'invoke',
  patchUiSession: 'send',
  onUiSessionChanged: 'push',
  getUiPreferences: 'invoke',
  setUiPreference: 'invoke'
} as const satisfies Record<keyof DwarfAiMinersApi, WindowApiMemberKind>

const MEMBERS: Readonly<Record<string, WindowApiMemberKind>> = WINDOW_API_MEMBERS

function notAMember(name: string): Error {
  return new Error(`window.api has no member "${name}": it is not a row of the channel registry`)
}

/** What a member does when a test did not fake it: an invoke rejects, so a missing answer is never silent. */
function unfaked(name: string, kind: WindowApiMemberKind): unknown {
  switch (kind) {
    case 'invoke':
      return () =>
        Promise.reject(new Error(`fake window.api: no answer for ${name}; pass one in overrides`))
    case 'send':
      return () => undefined
    case 'push':
      return () => () => undefined
    case 'helper':
      return () => ''
  }
}

/**
 * A fake `window.api` with every registry member: each override replaces its member, the others keep an inert
 * default. Overriding, or reading, a member the registry does not have throws, which fails the test.
 */
export function createFakeWindowApi(overrides: Partial<DwarfAiMinersApi> = {}): DwarfAiMinersApi {
  const given: Readonly<Record<string, unknown>> = overrides
  for (const name of Object.keys(given)) if (!Object.hasOwn(MEMBERS, name)) throw notAMember(name)
  const api: Record<string, unknown> = {}
  for (const [name, kind] of Object.entries(MEMBERS)) api[name] = given[name] ?? unfaked(name, kind)
  // `then` is read by `await` on any value; it is not a member and reads as undefined.
  return new Proxy(api, {
    get(target, key, receiver) {
      if (typeof key === 'string' && key !== 'then' && !Object.hasOwn(MEMBERS, key))
        throw notAMember(key)
      return Reflect.get(target, key, receiver)
    }
  }) as unknown as DwarfAiMinersApi
}
